examples/custom-email-templates/README.md, examples/custom-email-templates/en/email-confirm-change/body.html, examples/custom-email-templates/en/email-confirm-change/subject.txt, examples/custom-email-templates/en/email-verify/body.html, examples/custom-email-templates/en/email-verify/subject.txt, examples/custom-email-templates/en/password-reset/body.html, examples/custom-email-templates/en/password-reset/subject.txt, examples/custom-email-templates/en/signin-passwordless/body.html, examples/custom-email-templates/en/signin-passwordless/subject.txt, examples/custom-email-templates/fr/email-confirm-change/body.html, examples/custom-email-templates/fr/email-confirm-change/subject.txt, examples/custom-email-templates/fr/email-verify/body.html, examples/custom-email-templates/fr/email-verify/subject.txt, examples/custom-email-templates/fr/password-reset/body.html, examples/custom-email-templates/fr/password-reset/subject.txt, examples/custom-email-templates/fr/signin-passwordless/body.html, examples/custom-email-templates/fr/signin-passwordless/subject.txt
this example will have to be merged before next hasura-auth release (most likely today)
=> docs: custom email templates example

docs/styles/markdown-styles.module.css
=> fix: List item font size and font weight in docs

docs/components/AnchorLink.tsx, docs/components/MDX/CodeComponent.tsx, docs/components/MDX/components.tsx, docs/components/Nav.tsx, docs/components/ui/Text/Text.tsx, docs/components/ui/Text/index.ts, docs/pages/[category]/[subcategory].tsx
This PR aims to improve TypeScript definitions of MDX components to prevent warnings indicated by the compiler. A runtime error got also fixed, where `key` was not assigned to the wrapper of navigation items, because of an unnecessary React fragment.
=> Improved TypeScript definitions of MDX components

docs/components/Nav.tsx
Fixes #171.
This PR also fixes a `key` property related issue in sidebar and some typos in `Nav` component.
=> fix: Clickable sidebar section headers in Docs

docs/components/Nav.tsx
This PR aims to fix an accessibility issue, where navigation links were not working when they were clicked around the edges.
=> fix: increased clickable area of navigation links in Docs

.changeset/metal-months-reply.md, packages/hasura-auth-js/src/hasura-auth-api.ts, packages/hasura-storage-js/src/hasura-storage-api.ts, packages/nhost-js/src/clients/functions.ts, packages/nhost-js/src/clients/graphql.ts, packages/nhost-js/src/types.ts
See: https://github.com/vitejs/vite/discussions/6397
=> fix: import axios in using `require()` to avoid `XMLHttpRequest is not defined`

docs/components/MDX/components.tsx, docs/styles/markdown-styles.module.css
This PR fixes #169 and fixes #170 .
=> fix: docs: Ordered and unordered list markers, table typography

docs/content/docs/get-started/cli-workflow/install-cli.mdx, docs/content/docs/reference/sdk/authentication.mdx
This PR adds function reference of `onAuthStateChange` to the docs.
=> docs: onAuthStateChange function reference

docs/components/MDX/components.tsx
Remove border images and alt props from docs.
=> docs: Remove border & alt props from images.

examples/nextjs/pages/index.tsx, packages/react/src/hooks/storage.ts
add basic input fields to the main page, and create a basic readme
=> docs: improve NextJS example

packages/nhost-js/README.md
Fix wrong text in GraphQL section
=> Fix(nhost-js): Fix typo in README

.changeset/eighty-toes-eat.md, packages/hasura-storage-js/src/hasura-storage-api.ts, packages/hasura-storage-js/src/hasura-storage-client.ts
This PR fixes the conditions of how authentication headers are appended to storage functions.
=> fix: Auth header condition check

packages/react-auth/README.md
[rendered readme](https://github.com/nhost/nhost/tree/elitan-patch-1/packages/react-auth)
=> fix: make it clear the `@nhost/react-auth` package is depricated

.changeset/big-crews-smash.md, packages/apollo/package.json, packages/hasura-auth-js/package.json, packages/hasura-auth-js/src/hasura-auth-client.ts, packages/nextjs/package.json, packages/nhost-js/package.json, packages/react-apollo/package.json, packages/react-auth/package.json, packages/react/package.json, pnpm-lock.yaml
=> fix: correct access to user/session information through getUser/getSession/isReady

.changeset/brown-eggs-carry.md, packages/apollo/src/index.ts
=> fix: Query refetch and leaking GraphQL subscription

examples/nextjs/package.json, examples/nextjs/yarn.lock, examples/react-apollo/package.json, examples/react-apollo/src/profile/change-password.tsx, examples/react-apollo/src/sign-in/forgot-password.tsx, examples/react-apollo/yarn.lock
and remove workaround related to https://github.com/rsuite/rsuite/issues/2336
=> docs: bump dependencies of react-apollo and nextjs examples

docs/content/docs/get-started/quick-start/javascript-client.mdx
Separated the commands for installation according to the package managers.
=> Separated the commands for installation

.changeset/spotty-cycles-return.md, examples/nextjs/package.json, examples/nextjs/yarn.lock, examples/react-apollo/index.html, examples/react-apollo/nhost/metadata/databases/default/tables/auth_provider_requests.yaml, examples/react-apollo/package.json, examples/react-apollo/src/About.tsx, examples/react-apollo/src/App.tsx, examples/react-apollo/src/Home.tsx, examples/react-apollo/src/apollo/index.tsx, examples/react-apollo/src/components/auth-gates.tsx, examples/react-apollo/src/components/email-passwordless-form.tsx, examples/react-apollo/src/components/oauth-links.tsx, examples/react-apollo/src/env.d.ts, examples/react-apollo/src/main.tsx, examples/react-apollo/src/profile/change-email.tsx, examples/react-apollo/src/profile/change-password.tsx, examples/react-apollo/src/profile/index.tsx, examples/react-apollo/src/profile/mfa.tsx, examples/react-apollo/src/sign-in/email-password.tsx, examples/react-apollo/src/sign-in/email-passwordless.tsx, examples/react-apollo/src/sign-in/forgot-password.tsx, examples/react-apollo/src/sign-in/index.tsx, examples/react-apollo/src/sign-up/email-password.tsx, examples/react-apollo/src/sign-up/email-passwordless.tsx, examples/react-apollo/src/sign-up/index.tsx, examples/react-apollo/src/verification-email-sent.tsx, examples/react-apollo/yarn.lock, packages/react-apollo/README.md
=> Update examples to bump versions & hooks syntax, and fix dead link in react-apollo readme

tsconfig.json
See https://github.com/microsoft/TypeScript/issues/14619
=> fix: don't remove comments so they are present in the built .d.ts

.changeset/ninety-penguins-give.md, .changeset/selfish-flowers-sleep.md, .changeset/small-rabbits-act.md, packages/core/src/machines/index.ts, packages/core/src/machines/index.typegen.ts, packages/hasura-auth-js/src/hasura-auth-client.ts, packages/hasura-auth-js/src/utils/types.ts
- Trigger onTokenChanged when token changes
- Set onTokenChanged before the state interpreter started
- Add TSDoc information about Nhost client options
=> fix onTokenChanged

docs/docs/get-started/upgrade/index.md
=> Fixed typos in migration doc

.changeset/afraid-books-greet.md, packages/nhost-js/src/clients/functions.ts, packages/nhost-js/src/clients/graphql.ts, packages/nhost-js/src/types.ts, packages/nhost-js/tests/graphql.test.ts
Add generic types for NhostClient request return type and variables. This improves developer experience.
Fixes https://github.com/nhost/nhost/issues/404
(My first PR in this project 🎉 )
=> feat: Add generic types for NhostFunctionsClient and NhostGraphqlClient request method return type and variables

docs/docs/get-started/cli-workflow/metadata-and-serverless-functions.mdx, docs/docs/get-started/quick-start/javascript-client.md, docs/docs/platform/nhost/local-development.md, docs/docs/reference/nextjs/configuration.md, docs/docs/reference/react/apollo.md, docs/docs/reference/react/getting-started.md, docs/docs/reference/sdk/index.md
GraphQL dependency introduced [here](https://github.com/nhost/nhost/pull/414)
=> docs: use docusaurus tabs for npm/yarn commands, and add `graphql` dependency

.changeset/funny-candles-play.md, packages/core/package.json, packages/core/src/client.ts, packages/core/src/machines/index.ts, pnpm-lock.yaml
Fix https://github.com/nhost/nhost/issues/419
=> fix: remove broadcast-channel

docs/docs/get-started/quick-start/permissions.md
Changed the wording for a better understanding of the permissions doc
=> Changed the wording for better understanding

docs/docs/platform/serverless-functions/event-triggers.md
Show how environment variables are used with the correct formatting. I had to search around a while to find the correct {{}} format.
=> Docs: Update event-triggers.md with environment variable example

docs/src/css/custom.css, docs/src/theme/NotFound.js
=> docs: custom 404 page

docs/docusaurus.config.js
app id / key / index does not seem to work
=> docs: enable algolia search

docs/docs/platform/quickstarts/react.mdx
Update the guide based on Johan's feedback + add a new section at the end to show how to use the GraphQL API to fetch user data + reflect changes from the provided template.
=> docs: Update React quickstart guide

docs/docs/platform/authentication/user-management.md
=> user-management: Specify metadata info

docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/11-is-authenticated.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/13-get-authentication-status.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/14-get-access-token.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/15-get-decoded-access-token.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/16-get-hasura-claims.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/17-get-hasura-claim.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/18-refresh-session.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/19-get-session.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/20-get-user.mdx, docs/docs/reference/docgen/javascript/auth/types/nhost-auth-constructor-params.mdx, docs/docs/reference/docgen/javascript/nhost-js/types/nhost-client-constructor-params.mdx, docs/docs/reference/docgen/javascript/storage/content/hasura-storage-client/content/01-upload.mdx, docs/docs/reference/docgen/nextjs/types/nhost-react-client-constructor-params.mdx, docs/docs/reference/docgen/react/types/nhost-react-client-constructor-params.mdx, docs/docs/reference/docgen/vue/types/nhost-vue-client-constructor-params.mdx, packages/core/src/types.ts, packages/docgen/src/fragments/CommentFragment.ts, packages/docgen/src/types/common.ts, packages/hasura-auth-js/src/hasura-auth-client.ts
=> fix: Auto-generated documentation descriptions

packages/apollo/README.md, packages/hasura-auth-js/README.md, packages/hasura-storage-js/README.md, packages/nextjs/README.md, packages/nhost-js/README.md, packages/react-apollo/README.md, packages/react/README.md, packages/vue/README.md
...so we can add links to awesome github repos, for instance https://github.com/vuejs/awesome-vue
=> basic package readmes

docs/src/css/custom.css
Highlighted code is unreadable in light mode.
Lighter highlight background color.
=> fix: Docusaurus highlight background color

.changeset/cold-teachers-sniff.md, config/vite.lib.config.js, package.json, packages/apollo/package.json, packages/core/package.json, packages/hasura-auth-js/package.json, packages/hasura-storage-js/package.json, packages/nextjs/package.json, packages/nhost-js/package.json, packages/react-apollo/package.json, packages/react-auth/package.json, packages/react/package.json, packages/vue/package.json, pnpm-lock.yaml
- Fixed a couple of warnings occurring while building packages
- Fixed build step on Windows
=> Package build improvements

docs/docs/platform/graphql/permissions.md
Further instructions of how to handle custom permission variables in development.
=> Update permission variables section

docs/docs/platform/database/index.mdx
Updating the documentation to reflect the new location of the button to open Hasura Console.
=> Clarifying how to open Hasura Console

docs/docusaurus.config.js
Search working both in modal + full page.
Test here: https://docs-git-docs-algolio-fix-nhost.vercel.app/
=> Fix Algolia full page search

docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/03-sign-out.mdx
Edited line 34, from "decvices" to "devices"
=> Deleted typo error

docs/docs/platform/database/index.mdx, docs/docs/reference/cli/up.mdx
https://docs-git-docs-seed-nhost.vercel.app/platform/database#seed-data
=> docs: Added seed data information

packages/nextjs/README.md, packages/nhost-js/README.md, packages/nhost-js/tests/graphql.test.ts, packages/react-apollo/README.md, packages/react/README.md, packages/vue/README.md
there's still some refactoring to be done in examples and some packages (especially NextJs)
this PR is a low-hanging fruit
=> docs: update to subdomains in readmes

packages/apollo/package.json, packages/core/package.json, packages/docgen/package.json, packages/hasura-auth-js/package.json, packages/hasura-storage-js/package.json, packages/nextjs/package.json, packages/nhost-js/package.json, packages/react-apollo/package.json, packages/react-auth/package.json, packages/react/package.json, packages/vue/package.json
Add test coverage command in every package.
=> chore: add test coverage in every packages

examples/vue-apollo/src/components/ErrorSnackBar.vue, examples/vue-apollo/src/components/NavBar.vue, examples/vue-apollo/src/components/OAuthLinks.vue, examples/vue-apollo/src/main.ts, examples/vue-apollo/src/pages/sign-in/CommonActions.vue, examples/vue-apollo/src/pages/sign-in/EmailPassword.vue, examples/vue-apollo/src/pages/sign-in/EmailPasswordless.vue, examples/vue-apollo/src/pages/sign-in/IndexPage.vue, examples/vue-apollo/src/pages/sign-up/CommonActions.vue, examples/vue-apollo/src/pages/sign-up/EmailPassword.vue, examples/vue-apollo/src/pages/sign-up/EmailPasswordless.vue, examples/vue-apollo/src/pages/sign-up/IndexPage.vue, examples/vue-apollo/vercel.json
- lint fix/prettier
- correct redirections
- use the new subdomain syntax
- add vercel.json to handle redirections
- need to trigger the first Nhost deployment
=> Adapt Vue-Apollo example to live demo

.changeset/dull-pugs-scream.md, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/02-sign-in.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/05-change-password.mdx, docs/docs/reference/docgen/javascript/auth/types/api-change-email-response.mdx, docs/docs/reference/docgen/javascript/auth/types/api-change-password-response.mdx, docs/docs/reference/docgen/javascript/auth/types/api-deanonymize-response.mdx, docs/docs/reference/docgen/javascript/auth/types/api-refresh-token-response.mdx, docs/docs/reference/docgen/javascript/auth/types/api-reset-password-response.mdx, docs/docs/reference/docgen/javascript/auth/types/api-send-verification-email-response.mdx, docs/docs/reference/docgen/javascript/auth/types/api-sign-in-data.mdx, docs/docs/reference/docgen/javascript/auth/types/api-sign-in-response.mdx, docs/docs/reference/docgen/javascript/auth/types/api-sign-out-response.mdx, docs/docs/reference/docgen/javascript/auth/types/api-sign-up-email-password-response.mdx, docs/docs/reference/docgen/javascript/auth/types/auth-change-event.mdx, docs/docs/reference/docgen/javascript/auth/types/auth-changed-function.mdx, docs/docs/reference/docgen/javascript/auth/types/change-email-params.mdx, docs/docs/reference/docgen/javascript/auth/types/change-password-params.mdx, docs/docs/reference/docgen/javascript/auth/types/deanonymize-params.mdx, docs/docs/reference/docgen/javascript/auth/types/headers.mdx, docs/docs/reference/docgen/javascript/auth/types/mfa.mdx, docs/docs/reference/docgen/javascript/auth/types/on-token-changed-function.mdx, docs/docs/reference/docgen/javascript/auth/types/send-verification-email-params.mdx, docs/docs/reference/docgen/javascript/auth/types/sign-in-reponse.mdx, packages/hasura-auth-js/src/hasura-auth-client.ts, pnpm-lock.yaml
Updated the Nhost reference docs to align with the E.164 formatting standard that is required to send out an OTP.
main docs: https://docs.nhost.io/platform/authentication/sign-in-with-phone-number-sms
reference docs: https://docs.nhost.io/reference/javascript/auth/sign-in
=> Update for reference docs 02-sign-in.mdx

.changeset/new-oranges-bathe.md, packages/react-apollo/src/provider.tsx
Thanks @GavanWilhite for pinpointing the issue 🙌🏼 
This should fix #873.
=> fix (react-apollo): broken Next.js SSG

examples/react-apollo/src/sign-in/email-password.tsx, examples/react-apollo/src/sign-in/email-passwordless.tsx, examples/react-apollo/src/sign-in/security-key.tsx, examples/react-apollo/src/sign-up/email-password.tsx, examples/react-apollo/src/sign-up/email-passwordless.tsx, examples/react-apollo/src/sign-up/security-key.tsx
Add missing "other sign-in/out methods" buttons
=> Improve navigation in the react-apollo example

.changeset/orange-geckos-pull.md, packages/stripe-graphql-js/src/schema/stripe.ts, packages/stripe-graphql-js/src/types.ts
fixes issue: https://github.com/nhost/nhost/issues/980
=> feat/added async support for isAllowed prop for createStripeGraphQLServer

.changeset/fuzzy-paws-raise.md, packages/stripe-graphql-js/src/schema/customer.ts
=> Add description for all Stripe GraphQL Fields

.changeset/four-bobcats-roll.md, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/01-sign-up.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/02-sign-in.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/03-sign-out.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/04-reset-password.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/05-change-password.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/06-send-verification-email.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/07-change-email.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/08-deanonymize.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/09-add-security-key.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/10-on-token-changed.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/11-on-auth-state-changed.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/12-is-authenticated.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/13-is-authenticated-async.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/14-get-authentication-status.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/15-get-access-token.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/16-get-decoded-access-token.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/17-get-hasura-claims.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/18-get-hasura-claim.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/19-refresh-session.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/20-get-session.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/content/21-get-user.mdx, docs/docs/reference/docgen/javascript/auth/content/hasura-auth-client/index.mdx, packages/core/src/errors.ts, packages/hasura-auth-js/src/hasura-auth-client.ts
=> fix: 🐛 `nhost.auth.signIn()` to sign in anonymously

.github/workflows/changesets.yaml, examples/multi-tenant-one-to-many/package.json, pnpm-lock.yaml
The changeset GH action is not functioning as expected since the pnpm upgrade
=> fix: changeset gh action and dependencies

.changeset/dull-meals-arrive.md, packages/core/src/machines/index.ts, packages/core/src/machines/index.typegen.ts, packages/core/tests/refreshToken.test.ts
https://discord.com/channels/552499021260914688/1032338903186817055/1032338903186817055
=> fix: 🐛 Do not create an authentication error when starting with no refresh token

examples/react-apollo/nhost/config.yaml, examples/react-apollo/package.json
Vite is using `http://127.0.0.1:5173`.
=> Correct client url

docs/docs/quickstarts/vue.mdx
https://docs.nhost.io/quickstarts/vue#update-user-data
=> Vue docs fix: «client» → «nhost»

.changeset/brown-planets-build.md, dashboard/src/components/settings/signInMethods/AppleProviderSettings/AppleProviderSettings.tsx, dashboard/src/components/settings/signInMethods/DiscordProviderSettings/DiscordProviderSettings.tsx, dashboard/src/components/settings/signInMethods/FacebookProviderSettings/FacebookProviderSettings.tsx, dashboard/src/components/settings/signInMethods/GitHubProviderSettings/GitHubProviderSettings.tsx, dashboard/src/components/settings/signInMethods/GoogleProviderSettings/GoogleProviderSettings.tsx, dashboard/src/components/settings/signInMethods/LinkedInProviderSettings/LinkedInProviderSettings.tsx, dashboard/src/components/settings/signInMethods/SpotifyProviderSettings/SpotifyProviderSettings.tsx, dashboard/src/components/settings/signInMethods/TwitchProviderSettings/TwitchProviderSettings.tsx, dashboard/src/components/settings/signInMethods/TwitterProviderSettings/TwitterProviderSettings.tsx, dashboard/src/components/settings/signInMethods/WindowsLiveProviderSettings/WindowsLiveProviderSettings.tsx, dashboard/src/components/settings/signInMethods/WorkOsProviderSettings/WorkOsProviderSettings.tsx
- fixes the redirect url for oauth providers
=> fix(dashboard): correct redirect URL for oauth providers

.changeset/hip-coats-pump.md, packages/nextjs/package.json
Closes #1170
@elitan any possible breaking change introduced by Next 13?
=> chore: nextjs 13

.changeset/mean-cats-explain.md
=> chore: correct changeset from major to patch

docs/docs/graphql/permissions.mdx
See https://discord.com/channels/552499021260914688/1044990388324274246
=> docs: custom claims and singleton arrays

.changeset/neat-moose-jam.md, dashboard/src/pages/_document.tsx, dashboard/src/pages/index.tsx
This PR should trigger a staging deployment, but not a production deployment.
=> fix(dashboard): update terminology

config/.eslint.base.js, package.json, packages/docgen/.eslintrc.js, pnpm-lock.yaml
@szilarddoro this one's for you 😃
=> chore: remove eslint plugin simple-import-sort

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> chore: create issue templates

.changeset/lemon-crabs-bow.md, dashboard/src/components/settings/environmentVariables/BaseEnvironmentVariableForm/BaseEnvironmentVariableForm.tsx
=> fix(dashboard): remove character limit from env var inputs

.github/renovate.json
Add a renovate label to the related pull requests to we better identify them in the list
=> ci: add renovate label

.github/labeler.yaml
Automatically add labels to pull requests depending on changed files
=> chore: add labels to pull requests

.github/workflows/labeler.yaml
See https://github.com/actions/labeler/issues/442
=> chore: don't remove existing labels

dashboard/package.json, pnpm-lock.yaml
The last version bump messed up something with Emotion / MUI, and caused a weird error with sidebar elements on staging. Now it's working fine again.
Related PR: https://github.com/nhost/nhost/pull/1302
=> chore(dashboard): revert `@types/react` bump

docs/docs/cli/local-development.mdx
I wasn't able to see any docs on seed data, but being able to reset them and manage them is really useful for local development!
=> Add a section on managing local seed data

.changeset/warm-countries-peel.md, dashboard/src/components/settings/signInMethods/AppleProviderSettings/AppleProviderSettings.tsx, dashboard/src/utils/settings/settingsConstants/settingsConstants.tsx
Link to bug report:
https://discord.com/channels/552499021260914688/1050478799332065301
=> fix(dashboard): do not show error when submitting Apple provider settings

.changeset/hip-pumpkins-begin.md, dashboard/src/components/overview/OverviewProjectInfo/OverviewProjectInfo.tsx, dashboard/src/hooks/useCurrentWorkspaceAndApplication.tsx
=> fix(dashboard): don't break UI when region is nullish

docs/docs/quickstarts/vue.mdx, examples/vue-quickstart/src/components/Footer.vue, examples/vue-quickstart/src/pages/index.vue, examples/vue-quickstart/src/pages/profile.vue, examples/vue-quickstart/src/pages/sign-in.vue, examples/vue-quickstart/src/pages/sign-up.vue
As discussed in #1343 please find an update to the Vue Quckstart documentation.
The changes includes:
- switch to new `NhostClient()` syntax
- clarification of environment variables usage
- highlighting of Hasura update permissions step
- confirmation of the work-flow being correct and error free
- highlighting of all code changes / additions in code snippets
- minor code formatting changes (standardisation)
- minor typo and word choice changes
- minor Markdown formatting changes to improve readability
I hope the above changes are acceptable.
=> Update of Vue Quickstart documentation

packages/hasura-auth-js/src/hasura-auth-client.ts
I was overriding some code that I shouldn't have in a previous PR:
https://github.com/nhost/nhost/pull/1228/files#diff-0dbc30932ed723b7fd458066893f29f2f77658436c84adf42613813ea042c992R433-R459
This caused CI to fail.
This PR should fix it.
=> revert code to previously working

.changeset/proud-hotels-pretend.md, packages/react/src/useAuthInterpreter.ts
=> fix: improve missing React provider error

.changeset/afraid-clouds-eat.md, packages/react/src/client.ts, turbo.json
[Docs preview](https://docs-ifrbyam0z-nhost.vercel.app/reference/react)
Closes https://github.com/nhost/nhost/issues/1456
=> Only export what is required by the user or `@nhost/nextjs`

.changeset/rude-melons-rest.md, dashboard/src/components/common/DialogProvider/DialogContext.ts, dashboard/src/components/common/DialogProvider/DialogProvider.tsx, dashboard/src/components/settings/environmentVariables/EditJwtSecretForm/EditJwtSecretForm.tsx, dashboard/src/components/settings/environmentVariables/EditJwtSecretForm/index.ts, dashboard/src/components/settings/environmentVariables/SystemEnvironmentVariableSettings/SystemEnvironmentVariableSettings.tsx
**Preview URL:** https://dashboard-staging-git-feat-custom-jwt-secret-nhost.vercel.app
Fixes: https://github.com/nhost/nhost/issues/1455
=> feat(dashboard): add JWT secret editor modal

.changeset/rude-sloths-lay.md, examples/react-apollo/cypress/e2e/4-authenticated/file-uploads.cy.ts, packages/hasura-storage-js/src/machines/file-upload.ts, packages/hasura-storage-js/src/machines/file-upload.typegen.ts, packages/react/src/useFileUpload.ts, packages/vue/src/useFileUpload.ts
Fixes https://github.com/nhost/nhost/issues/865
=> fix: 🐛 allow useFileUpload to be reused

.changeset/chatty-rabbits-learn.md, dashboard/src/types/logs.ts, dashboard/src/utils/logs.ts
=> feat(dashboard): add functions to logs

.changeset/red-donuts-marry.md, dashboard/src/components/users/CreateUserForm/CreateUserForm.tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/users/index.tsx
fixes: https://github.com/nhost/nhost/issues/1474
=> fix(dashboard): create new user

.github/actions/nhost-cli/action.yaml, examples/react-apollo/cypress/e2e/1-unauthenticated/forgot-password.cy.ts, examples/react-apollo/cypress/support/e2e.ts
and higher number of attempts to install the Nhost CLI
=> test: correct forgot-password test

docs/docs/quickstarts/nextjs.mdx
=> Docs: Fix npm install command

.changeset/curvy-planets-exercise.md, dashboard/src/components/applications/AppDeployments.tsx, dashboard/src/components/deployments/AppDeploymentDuration/AppDeploymentDuration.tsx, dashboard/src/components/deployments/DeploymentListItem/DeploymentListItem.tsx, dashboard/src/components/overview/OverviewDeployments/OverviewDeployments.tsx, dashboard/src/components/ui/StatusCircle.tsx, dashboard/src/gql/deployments/deployments.graphql, dashboard/src/pages/[workspaceSlug]/[appSlug]/deployments/[deploymentId].tsx, dashboard/src/utils/__generated__/graphql.ts
This is a follow-up PR for https://github.com/nhost/nhost/pull/1503. Also, fixes an issue where the "Live" badge was shown for every deployment that was the first on the page on the "Deployments" page.
Preview: https://dashboard-staging-git-fix-retrigger-deployment-status-nhost.vercel.app/
=> fix(dashboard): correct redeployment button

.changeset/silent-penguins-dream.md, dashboard/README.md, dashboard/src/components/settings/authentication/AllowedEmailSettings/AllowedEmailSettings.tsx, dashboard/src/components/settings/authentication/BlockedEmailSettings/BlockedEmailSettings.tsx
=> fix(dashboard): enable toggle when settings are filled in

.changeset/friendly-rice-swim.md, dashboard/src/components/users/CreateUserForm/CreateUserForm.tsx, dashboard/src/components/users/EditUserForm/EditUserForm.tsx, dashboard/src/components/users/UsersBody/UsersBody.tsx
Fixes https://github.com/nhost/nhost/issues/1481
=> fix(dashboard): don't break Auth page in local mode

.changeset/fluffy-bags-play.md, dashboard/src/components/settings/roles/BaseRoleForm/BaseRoleForm.tsx, dashboard/src/components/settings/roles/CreateRoleForm/CreateRoleForm.tsx, dashboard/src/components/settings/roles/RoleSettings/RoleSettings.tsx
The previous Roles section is renamed to Allowed Roles which is different from roles in general. Allowed roles are a subset of roles.
=> fix(dashboard): allowed roles

.changeset/exposes-believer-extinctions.md
This PR creates the changesets from the Renovate dependencies that have been merged to main.
=> chore: create changesest from Renovate bumps

dashboard/package.json, pnpm-lock.yaml
=> Revert "chore(deps): update dependency @types/react to v18.0.27"

.changeset/blue-nails-sparkle.md, .github/workflows/changesets.yaml, dashboard/Dockerfile
Related issue: https://github.com/vercel/turbo/issues/3564
=> chore(dashboard): restore Vercel build restrictions and fix Docker build

.changeset/mighty-spoons-nail.md, dashboard/src/components/dashboard/CountrySelector.tsx
fixes https://github.com/nhost/nhost/issues/1592
=> Use country code instead of name

docs/docs/reference/cli/init.mdx, docs/docs/reference/cli/list.mdx, docs/docs/reference/cli/logs.mdx, docs/docs/reference/cli/up.mdx
fixes: https://github.com/nhost/nhost/issues/1449
=> CLI docs updates.

.changeset/ninety-carrots-teach.md, .changeset/ten-donkeys-fly.md, packages/graphql-js/README.md, packages/graphql-js/nhost/metadata/databases/default/tables/public_tasks.yaml, packages/graphql-js/nhost/metadata/databases/default/tables/tables.yaml, packages/graphql-js/nhost/migrations/default/1677072568289_create_table_public_tasks/down.sql, packages/graphql-js/nhost/migrations/default/1677072568289_create_table_public_tasks/up.sql, packages/graphql-js/package.json, packages/graphql-js/src/graphql-object/schema.ts, packages/graphql-js/tests/codegen.yaml, packages/graphql-js/tests/schemas/hasura.ts, packages/graphql-js/tests/types/parameters.ts, pnpm-lock.yaml
we need a changeset if we want to re-publish the readme on https://www.npmjs.com
=> GraphQL client: fix snake_case bug and improve readme

.changeset/grumpy-fans-sip.md, dashboard/src/components/users/EditUserForm/EditUserForm.tsx
=> fix(dashboard): use correct date for last seen

.changeset/fast-experts-pretend.md, dashboard/src/components/users/CreateUserForm/CreateUserForm.tsx
**Preview URL**: https://dashboard-staging-git-fix-user-creation-content-type-nhost.vercel.app/
=> fix(dashboard): set correct Content-Type for user creation

.changeset/funny-laws-promise.md, .changeset/heavy-toes-sort.md, .changeset/itchy-dots-smash.md, .changeset/kind-ducks-hang.md, .changeset/many-pumas-fetch.md, .changeset/nervous-pants-join.md, .changeset/nine-bobcats-guess.md, packages/hasura-storage-js/src/hasura-storage-api.ts, packages/hasura-storage-js/src/utils/upload.ts
=> fix(hasura-storage-js): fix forbidden error

.changeset/hot-mangos-return.md, dashboard/package.json, dashboard/src/components/applications/ApplicationInfo.tsx, dashboard/src/components/applications/RenderWorkspacesWithApps.tsx, dashboard/src/components/deployments/DeploymentStatusMessage/DeploymentStatusMessage.test.tsx, dashboard/src/components/deployments/DeploymentStatusMessage/DeploymentStatusMessage.tsx, dashboard/src/components/deployments/DeploymentStatusMessage/index.ts, dashboard/src/components/ui/Avatar.tsx, pnpm-lock.yaml
This PR contains the following fixes:
- A fix for an issue [mentioned on our Discord](https://discord.com/channels/552499021260914688/1080458370672230420/1080458370672230420) affecting deployment dates
- A fix for an issue where the project list was not refreshed when using an internal solution to delete projects
- A fix for a warning caused by the recent introduction of `node-fetch`
=> fix(dashboard): show correct deployment status on the main page

.changeset/cyan-goats-remain.md, packages/nhost-js/src/clients/functions/index.ts
=> fix(nhost-js): correct return type in functions

.changeset/fuzzy-impalas-admire.md, dashboard/src/components/applications/ChangePlanModal.tsx, dashboard/src/components/applications/UnlockFeatureByUpgrading.tsx, dashboard/src/components/deployments/DeploymentListItem/DeploymentListItem.tsx, dashboard/src/components/deployments/DeploymentStatusMessage/DeploymentStatusMessage.tsx, dashboard/src/components/overview/OverviewDeployments/OverviewDeployments.tsx, dashboard/src/components/overview/OverviewTopBar/OverviewTopBar.tsx, dashboard/src/components/ui/v2/createTheme/createTheme.ts
The dashboard (e.g: overview, deployments, etc.) was broken on smaller screens. This PR tries to address some of the responsive layout issues.
=> fix(dashboard): improve mobile responsive layout

.changeset/nine-penguins-shop.md, examples/nextjs/helpers/index.tsx, examples/nextjs/pages/_app.tsx, examples/nextjs/pages/guarded-ssr.tsx, examples/nextjs/pages/public-ssr.tsx, packages/nextjs/README.md, packages/nextjs/src/create-server-side-client.ts, packages/nextjs/src/get-session.ts
=> fix(nextjs): allow `subdomain`, `region` and service URLs

.changeset/pretty-singers-taste.md, dashboard/src/components/settings/authentication/DisableNewUsersSettings/DisableNewUsersSettings.tsx
=> fix(dashboard): disable new users

.changeset/slimy-spies-fold.md, dashboard/src/components/common/DataGridDateCell/DataGridDateCell.tsx
=> fix(dashboard): show correct date in data grid

.changeset/popular-tigers-hug.md, packages/hasura-storage-js/package.json, packages/hasura-storage-js/src/hasura-storage-client.ts, packages/hasura-storage-js/src/utils/appendImageTransformationParameters/appendImageTransformationParameters.test.ts, packages/hasura-storage-js/src/utils/appendImageTransformationParameters/appendImageTransformationParameters.ts, packages/hasura-storage-js/src/utils/appendImageTransformationParameters/index.ts, packages/hasura-storage-js/src/utils/index.ts, packages/hasura-storage-js/src/utils/types.ts, packages/hasura-storage-js/vite.unit.config.js
=> fix(hasura-storage-js): allow image transformation parameters in `getPresignedUrl`

docs/docs/serverless-functions.mdx
=> fix DevDependencies parameter for @types/express

dashboard/e2e/auth/user-management.test.ts, dashboard/e2e/database/table-creation.test.ts, dashboard/e2e/overview/overview.test.ts, dashboard/e2e/utils.ts, dashboard/package.json, dashboard/playwright.config.ts, dashboard/tsconfig.json, dashboard/tsconfig.test.json, pnpm-lock.yaml
A few E2E tests have been added in this PR to cover the table creation process.
=> chore(dashboard): tests for table creation

.changeset/red-bananas-type.md, .changeset/shaggy-ghosts-chew.md, dashboard/.storybook/preview.js, dashboard/graphql.config.yaml, dashboard/package.json, dashboard/src/components/overview/OverviewDeployments/OverviewDeployments.test.tsx, dashboard/src/utils/msw/mocks/graphql/nhostGraphQLLink.ts, dashboard/src/utils/testUtils.tsx, integrations/apollo/package.json, integrations/apollo/src/index.ts, integrations/apollo/src/ws.ts, integrations/react-apollo/package.json, integrations/react-apollo/src/hooks.tsx, integrations/react-apollo/src/provider.tsx, pnpm-lock.yaml
This PR is a step toward fixing https://github.com/nhost/nhost/issues/1225 and also fixes an issue on our dashboard that caused weird errors when the subscription was abruptly closed.
=> fix(apollo): retry subscriptions on error

dashboard/src/components/settings/signInMethods/AzureADProviderSettings/AzureADProviderSettings.tsx
Use the same phrasing here as the other providers.
=> fix(dashboard): use correct description for Azure AD

.changeset/loud-jobs-mate.md, dashboard/src/components/logs/LogsTimePicker/LogsTimePicker.tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/database/browser/[dataSourceSlug]/index.tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/logs/index.tsx
Fixes this issue: https://discord.com/channels/552499021260914688/1092276818771460167/1092276818771460167
=> fix(dashboard): don't break logs page

.changeset/short-tables-teach.md, docs/docs/cli/index.mdx, docs/docs/cli/local-development.mdx, docs/docs/graphql/index.mdx, docs/docs/graphql/remote-schemas/stripe.mdx
With the change of local URLs to the subdomain format with "local" as subdiomain and no region, I believe these URLs should be updated here.
=> Update local URLs to new format

.changeset/giant-maps-fly.md, docs/docs/cli/index.mdx, docs/docusaurus.config.js, docs/src/css/custom.css
=> docs: add migration info

.changeset/shy-numbers-hide.md, .changeset/soft-humans-matter.md, dashboard/src/components/applications/ApplicationPaused.tsx, dashboard/src/components/applications/ChangePlanModal.tsx, dashboard/src/components/settings/ResetDatabasePasswordSettings/ResetDatabasePasswordSettings.tsx, dashboard/src/hooks/useNotFoundRedirect.tsx
This PR also fixes an issue where project creation sometimes redirected users to the 404 page.
=> fix(dashboard): unpause after upgrading a paused project to pro

.changeset/yellow-bananas-approve.md, config/vite.lib.config.js
=> chore: change build target to ES2019

.changeset/eighty-donkeys-admire.md, packages/hasura-auth-js/src/promises/addSecurityKey.ts
Fixes the issue mentioned here: https://discord.com/channels/552499021260914688/1105985515716612196/1105985515716612196
=> fix(hasura-auth-js): make the call to the correct endpoint

.changeset/metal-sheep-bathe.md, docs/docs/reference/javascript/index.mdx, docs/docs/reference/nextjs/index.mdx, docs/docs/reference/react/index.mdx, docs/docs/reference/vue/index.mdx
**Preview URL**: https://docs-git-docs-custom-urls-nhost.vercel.app/
=> docs: add section about using custom URLs

.changeset/yellow-chicken-accept.md, dashboard/src/features/hasura/settings/components/HasuraServiceVersionSettings/HasuraServiceVersionSettings.tsx, dashboard/src/features/projects/backups/components/BackupList/BackupList.tsx, dashboard/src/features/projects/backups/components/BackupList/index.ts, dashboard/src/features/projects/backups/components/BackupListItem/BackupListItem.tsx, dashboard/src/features/projects/backups/components/BackupListItem/index.ts, dashboard/src/features/projects/backups/components/RestoreBackupModal/RestoreBackupModal.tsx, dashboard/src/features/projects/backups/gql/backup.gql, dashboard/src/features/projects/backups/gql/getApplicationBackups.graphql, dashboard/src/features/projects/backups/gql/getBackupPresignedUrl.gql, dashboard/src/pages/[workspaceSlug]/[appSlug]/backups.tsx, dashboard/src/types/application.ts, dashboard/src/utils/__generated__/graphql.ts
**Preview URL**: https://dashboard-staging-git-feat-download-backups-nhost.vercel.app/signin
---
Resolves #1930
=> feat(dashboard): add download button to backups

.changeset/little-hornets-tell.md, dashboard/src/components/layout/SettingsSidebar/SettingsSidebar.tsx, dashboard/src/components/ui/v2/Alert/Alert.tsx, dashboard/src/data/features.json, dashboard/src/features/database/settings/components/DatabaseConnectionInfo/DatabaseConnectionInfo.tsx, dashboard/src/features/database/settings/components/ResetDatabasePasswordSettings/ResetDatabasePasswordSettings.tsx, dashboard/src/features/projects/common/components/StagingMetadata/StagingMetadata.tsx, dashboard/src/hooks/useLeaveConfirm/index.ts, dashboard/src/hooks/useLeaveConfirm/useLeaveConfirm.ts, dashboard/src/pages/new.tsx, dashboard/src/utils/copy/copy.ts, dashboard/src/utils/helpers/helpers.ts, dashboard/src/utils/toast/triggerToast.tsx
**Preview URL**: [dashboard-staging-git-chore-remove-password-input-nhost.vercel.app](https://dashboard-staging-git-chore-remove-password-input-nhost.vercel.app/)
---
Resolves #1974
=> chore(dashboard): remove password input from project creation

.changeset/angry-grapes-rush.md, dashboard/src/features/database/settings/components/ResetDatabasePasswordSettings/ResetDatabasePasswordSettings.tsx, dashboard/src/features/database/settings/components/ResetDatabasePasswordSettings/index.ts, dashboard/src/features/database/settings/gql/resetDatabasePassword.gql, dashboard/src/features/database/settings/utils/resetDatabasePasswordValidationSchema/resetDatabasePasswordValidationSchema.ts, dashboard/src/gql/database/resetPostgresPassword.graphql, dashboard/src/utils/__generated__/graphql.ts, dashboard/src/utils/toast/getColor.ts
**Preview URL**: https://dashboard-staging-git-fix-reset-password-nhost.vercel.app/
=> fix(dashboard): don't break the password reset flow

.changeset/dirty-planets-shout.md, .changeset/tame-apes-heal.md, packages/hasura-auth-js/e2e/email.test.ts, packages/hasura-auth-js/e2e/helpers.ts, packages/hasura-auth-js/e2e/password.test.ts, packages/hasura-auth-js/e2e/sign-in.test.ts, packages/hasura-auth-js/package.json, packages/hasura-auth-js/src/constants.ts, packages/hasura-auth-js/src/machines/authentication/context.ts, packages/hasura-auth-js/src/machines/authentication/machine.ts, packages/hasura-auth-js/src/utils/fetch.ts, packages/hasura-auth-js/tests/helpers/mocks/contextWithUser.ts, packages/hasura-auth-js/tests/refreshToken.test.ts, packages/hasura-auth-js/tests/sendVerificationEmail.test.ts, pnpm-lock.yaml
=> fix(hasura-auth-js): prevent infinite token refresh

dashboard/src/features/authentication/settings/components/WebAuthnSettings/WebAuthnSettings.tsx
=> fix(webauthn): don't break webauthn form on save

.changeset/kind-horses-act.md, dashboard/package.json, dashboard/src/features/authentication/users/components/EditUserPasswordForm/EditUserPasswordForm.tsx, pnpm-lock.yaml
=> fix(dashboard): use dynamic validation schema for password editing

.changeset/honest-islands-return.md, examples/node-storage/README.md, examples/node-storage/nhost/migrations/default/1688049013889_insert_into_storage_buckets/down.sql, examples/node-storage/nhost/migrations/default/1688049013889_insert_into_storage_buckets/up.sql, examples/node-storage/src/index.mjs, examples/node-storage/src/uploadToBucket.mjs, packages/hasura-storage-js/src/utils/upload.ts
This PR is a fix for the [issue mentioned on our Discord channel](https://discord.com/channels/552499021260914688/1123893547955933214/1123893547955933214). It wasn't caused by the latest hasura-storage-js release.
=> fix(hasura-storage-js): allow using custom buckets for upload

.changeset/light-tips-rush.md, .github/workflows/ci.yaml, examples/react-apollo/.secrets.example, packages/hasura-auth-js/.secrets.example, packages/hasura-storage-js/.secrets.example, packages/hasura-storage-js/src/machines/file-upload.ts, packages/nhost-js/.secrets.example
=> fix(hasura-storage-js): fix file upload

.changeset/fuzzy-cooks-hide.md, dashboard/src/pages/[workspaceSlug]/[appSlug]/users/index.tsx
A Quick fix to improve the user experience at users page which the limit is currently one and make worse to manage the user
=> fix: back to previous limit

.changeset/slow-pugs-battle.md, dashboard/src/features/projects/common/utils/generateAppServiceUrl/generateAppServiceUrl.test.ts, dashboard/src/features/projects/common/utils/generateAppServiceUrl/generateAppServiceUrl.ts
=> feat: change grafana url to point to dashboards

.changeset/wet-ravens-yawn.md, .github/workflows/ci.yaml, dashboard/src/features/projects/resources/settings/components/ResourcesConfirmationDialog/ResourcesConfirmationDialog.tsx
=> fix: show zero values when dedicated resources is disabled

.changeset/pretty-days-cheer.md, dashboard/src/features/services/components/ServicesList/ServicesList.tsx
=> fix(services): handle null values when editing a service

.changeset/unlucky-cobras-relax.md, dashboard/src/features/projects/logs/components/LogsHeader/LogsHeader.tsx, dashboard/src/features/services/components/ServiceForm/components/EnvironmentFormSection/EnvironmentFormSection.tsx
=> fix: nhost run enhancements

.changeset/orange-toes-clean.md, dashboard/src/features/projects/resources/settings/utils/resourceSettingsValidationSchema/resourceSettingsValidationSchema.ts, dashboard/src/features/services/components/ServiceForm/ServiceForm.tsx, dashboard/src/features/services/components/ServiceForm/components/ComputeFormSection/ComputeFormSection.tsx, dashboard/src/features/services/components/ServiceForm/components/ServiceConfirmationDialog/ServiceConfirmationDialog.tsx, dashboard/src/features/services/components/ServiceForm/components/ServiceConfirmationDialog/index.ts
=> feat: add pricing info and confirmation dialog

.changeset/few-kings-develop.md, dashboard/src/components/dataGrid/DataGridBody/DataGridBody.tsx
=> fix: grey out not uploaded files

.changeset/early-otters-rescue.md, packages/hasura-storage-js/src/utils/upload.ts
=> fix(hasura-storage-js): fix upload response status code check

.changeset/fair-students-wash.md, examples/react-apollo/src/components/OauthLinks.tsx
=> chore(react-apollo-example): remove facebook login

.changeset/thin-candles-float.md, examples/react-apollo/src/profile/security-keys.tsx, packages/hasura-auth-js/src/errors.ts
=> fix(hasura-auth-js): make sure CodifiedError works on non v8 browsers

.changeset/wicked-news-grow.md, dashboard/src/features/authentication/settings/gql/getAuthenticationSettings.gql, dashboard/src/features/authentication/users/components/EditUserForm/EditUserForm.tsx, dashboard/src/gql/app/getProjectLocales.graphql, dashboard/src/utils/__generated__/graphql.ts
=> fix: remove hardcoded locales

.changeset/young-donkeys-jog.md, dashboard/src/components/ui/v2/LinearProgress/LinearProgress.tsx, dashboard/src/features/projects/overview/components/OverviewMetrics/OverviewMetrics.tsx, dashboard/src/features/projects/overview/components/OverviewUsage/OverviewUsage.tsx, dashboard/src/gql/app/getProjectMetrics.gql, dashboard/src/utils/__generated__/graphql.ts
=> feat(dashboard): update usage metrics

.changeset/brave-clouds-wonder.md, dashboard/src/features/projects/common/components/DeleteServiceModal/DeleteServiceModal.tsx, dashboard/src/features/projects/common/components/DeleteServiceModal/index.ts, dashboard/src/features/services/components/ServicesList/ServicesList.tsx
=> feat: run: delete service confirmation dialog

.changeset/lazy-carpets-hammer.md, dashboard/src/features/projects/resources/settings/components/TotalResourcesFormFragment/TotalResourcesFormFragment.tsx
=> fix: make sure dedicated resources pricing follows total resources

.changeset/nervous-dogs-exist.md, docs/docs/database/settings.mdx, docs/docs/graphql/permissions.mdx
=> chore(docs): added jit settings documentation

.github/workflows/changesets.yaml
Reference: https://github.com/changesets/action/blob/2bb9bcbd6bf4996a55ce459a630a0aa699457f59/README.md?plain=1#L14
=> chore(ci): disable automatic GitHub releases

.changeset/quick-crabs-sell.md, dashboard/src/features/projects/environmentVariables/settings/components/BaseEnvironmentVariableForm/BaseEnvironmentVariableForm.tsx
fixes #2279
Note: the value input for secrets already supports multiline
=> feat(dashboard): make env value input multiline

.changeset/quiet-monkeys-cheer.md, packages/vue/src/helpers.ts
=> fix(vue-sdk): correctly unref arrays

.changeset/hungry-experts-wonder.md, dashboard/src/components/common/DepricationNotice/DepricationNotice.tsx, dashboard/src/components/common/DepricationNotice/index.ts, dashboard/src/components/layout/AuthenticatedLayout/AuthenticatedLayout.tsx, dashboard/src/components/layout/SettingsLayout/SettingsLayout.tsx, dashboard/src/components/settings/ProvidersUpdatedAlert.tsx, dashboard/src/components/settings/index.ts, dashboard/src/gql/settings/confirmProvidersUpdated.gql, dashboard/src/pages/[workspaceSlug]/[appSlug]/backups.tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/database/browser/[dataSourceSlug]/index.tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/deployments/[deploymentId].tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/deployments/index.tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/graphql.tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/hasura/index.tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/index.tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/logs/index.tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/metrics/index.tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/services/index.tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/settings/sign-in-methods/index.tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/storage/index.tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/users/index.tsx, dashboard/src/utils/__generated__/graphql.ts
=> chore(dashboard): show oauth providers update notice

.changeset/long-berries-divide.md, integrations/apollo/src/index.ts
ref: https://github.com/nhost/nhost/pull/2309#discussion_r1356339598
=> fix: integrations: apollo: correct accessToken nullability test

.changeset/quick-swans-tie.md, packages/react/src/useChangePassword.ts
=> fix: update useChangePassword hook interface

observability/dashboards/ingress_metrics.json
=> fix (observability): ingress tenant dashboard

examples/react-apollo/nhost/nhost.toml
=> fix(react-apollo): update Apple OAuth secrets in nhost.toml

.changeset/lazy-games-deny.md, dashboard/src/features/account/settings/components/DeleteAccount/DeleteAccount.tsx, dashboard/src/features/account/settings/components/DeleteAccount/index.ts, dashboard/src/features/account/settings/gql/deleteUserAccount.gql, dashboard/src/pages/account/index.tsx, dashboard/src/utils/__generated__/graphql.ts
=> feat: delete account

dashboard/Dockerfile
=> chore: update node to v18

.changeset/wise-geese-attend.md, dashboard/src/features/authentication/settings/gql/getAuthenticationSettings.gql, dashboard/src/features/database/settings/gql/getPostgresSettings.gql, dashboard/src/features/hasura/settings/gql/getHasuraSettings.gql, dashboard/src/features/projects/resources/settings/gql/getResources.gql, dashboard/src/features/storage/settings/gql/getStorageSettings.gql, dashboard/src/gql/app/getProjectLocales.graphql, dashboard/src/gql/app/settings/environmentVariables/getEnvironmentVariables.graphql, dashboard/src/gql/app/settings/rolesPermissions/getRolesPermissions.graphql, dashboard/src/gql/app/settings/signInMethods/getSignInMethods.graphql, dashboard/src/gql/app/settings/smtp/getSmtpSettings.graphql, dashboard/src/gql/fragments/project.gql, dashboard/src/utils/__generated__/graphql.ts
=> fix: make sure secrets are not resolved

dashboard/src/features/projects/custom-domains/settings/components/ServerlessFunctionsDomain/ServerlessFunctionsDomain.tsx, dashboard/src/features/projects/custom-domains/settings/components/ServerlessFunctionsDomain/index.ts, dashboard/src/features/serverless-functions/settings/gql/setServerlessFunctionsSettings.gql, dashboard/src/pages/[workspaceSlug]/[appSlug]/settings/custom-domains/index.tsx, dashboard/src/utils/__generated__/graphql.ts
resolves https://github.com/nhost/be/issues/524
=> feat(dashboard): add serverless functions custom domain settings

.changeset/spicy-donuts-cry.md, examples/quickstarts/sveltekit/src/lib/nhost.js
fixes https://github.com/nhost/projects/issues/51
=> fix(quickstarts): fix auth issue and too many redirects error

.changeset/slimy-avocados-remain.md, dashboard/src/features/projects/roles/settings/components/RoleSettings/RoleSettings.tsx, docs/docs/authentication/users.mdx
- fixes https://github.com/nhost/nhost/issues/1561
- related to https://github.com/nhost/nhost/pull/1864
=> chore: change `Allowed Roles` to `Default Allowed Roles`

.changeset/thick-poets-jog.md, dashboard/src/features/ai/settings/components/AISettings.tsx, dashboard/src/features/authentication/settings/components/AuthServiceVersionSettings/AuthServiceVersionSettings.tsx, dashboard/src/features/database/settings/components/DatabaseServiceVersionSettings/DatabaseServiceVersionSettings.tsx, dashboard/src/features/hasura/settings/components/HasuraServiceVersionSettings/HasuraServiceVersionSettings.tsx, dashboard/src/features/storage/settings/components/HasuraServiceVersionSettings/StorageServiceVersionSettings.tsx
fixes https://github.com/nhost/nhost/issues/2434
=> fix: remove hardcoded ai settings version

.changeset/polite-countries-dream.md, docs/reference/openapi-auth.yaml
- https://github.com/nhost/nhost/issues/2474
=> fix: docs: remove auth method

.changeset/friendly-kiwis-stare.md, dashboard/next.config.js, dashboard/package.json, dashboard/src/features/projects/common/components/ChangePlanModal/ChangePlanModal.tsx, examples/codegen-react-apollo/package.json, examples/nextjs/package.json, examples/quickstarts/nextjs-server-components/package.json, examples/react-apollo/package.json, examples/vue-apollo/package.json, examples/vue-quickstart/package.json, integrations/apollo/package.json, integrations/react-apollo/package.json, pnpm-lock.yaml
related to https://github.com/nhost/nhost/issues/2530
=> fix(dashboard): resolve change plan modal cache issue

.changeset/strong-carpets-push.md, docs/guides/database/configuring-postgres.mdx, docs/guides/database/performance.mdx, docs/guides/storage/cdn.mdx, docs/mint.json, docs/platform/compute-resources.mdx, docs/product/storage.mdx
=> chore: docs: added a note about disk performance and CDN information

.changeset/wicked-badgers-sniff.md, dashboard/src/components/dataGrid/DataGridHeader/DataGridHeader.tsx
fixes https://github.com/nhost/nhost/issues/2526
=> fix: refactor DataGridHeader component to allow for selecting all rows

.changeset/fluffy-apples-prove.md, dashboard/src/components/ui/v2/ErrorToast/ErrorToast.tsx
fixes https://github.com/nhost/nhost/issues/2525
=> fix(dashboard): handle `Error` alongside `ApolloError` properly in the `ErrorToast` component

.changeset/blue-camels-train.md, dashboard/src/features/database/dataGrid/hooks/useRunSQL/useRunSQL.ts
fixes https://github.com/nhost/projects/issues/52
=> fix(dashboard): refresh table list after running a SQL stmt using the editor

.changeset/spicy-plants-work.md, dashboard/src/features/services/components/ServiceForm/ServiceForm.tsx, dashboard/src/features/services/components/ServiceForm/ServiceFormTypes.ts, dashboard/src/features/services/components/ServiceForm/components/HealthCheckFormSection/HealthCheckFormSection.tsx, dashboard/src/features/services/components/ServiceForm/components/HealthCheckFormSection/index.ts, dashboard/src/gql/services/getRunServices.graphql, dashboard/src/utils/__generated__/graphql.ts
fixes https://github.com/nhost/nhost/issues/2410
=> feat: dashboard: add healthcheck config to run services

.changeset/bright-rivers-judge.md, dashboard/src/components/dataGrid/DataGridBody/DataGridBody.tsx, dashboard/src/components/dataGrid/DataGridCell/DataGridCell.tsx, dashboard/src/features/database/dataGrid/components/DataBrowserGrid/DataBrowserGrid.tsx, dashboard/src/features/database/dataGrid/components/DataBrowserGridControls/DataBrowserGridControls.tsx, dashboard/src/features/database/dataGrid/hooks/useDeleteRecordMutation/deleteRecord.ts
fixes https://github.com/nhost/nhost/issues/2476
=> fix: dashboard: refactor database datagrid to allow insert/update/delete for tables `auth` and `storage`

.changeset/kind-chefs-unite.md, dashboard/src/features/ai/settings/components/AISettings.tsx, dashboard/src/features/ai/settings/gql/getAISettings.gql, dashboard/src/utils/__generated__/graphql.ts
fixes https://github.com/nhost/nhost/issues/2439
=> feat: dashboard: add min postgres version check to enable the ai service

.changeset/little-ducks-wait.md
adds missing changeset for this PR https://github.com/nhost/nhost/pull/2574
=> chore: add changeset

.changeset/calm-bottles-do.md, examples/react-apollo/nhost/emails/en/email-verify/body.html, examples/react-apollo/nhost/emails/en/password-reset/body.html, examples/react-apollo/nhost/emails/en/signin-passwordless/body.html, examples/react-apollo/nhost/nhost.toml, examples/react-apollo/src/App.tsx, examples/react-apollo/src/Verify.tsx, examples/vue-apollo/nhost/emails/en/email-verify/body.html, examples/vue-apollo/nhost/emails/en/password-reset/body.html, examples/vue-apollo/nhost/nhost.toml, examples/vue-apollo/src/pages/VerifyEmail.vue, examples/vue-apollo/src/pages/sign-in/EmailPassword.vue, examples/vue-apollo/src/pages/sign-in/ForgotPassword.vue, examples/vue-apollo/src/routes.ts
fixes https://github.com/nhost/nhost/issues/2314
=> feat(examples): add reset password ticket expired workarounds in the examples

.changeset/tender-maps-try.md, dashboard/src/features/account/settings/components/DisplayNameSetting/DisplayNameSetting.tsx, dashboard/src/features/account/settings/components/DisplayNameSetting/index.ts, dashboard/src/features/account/settings/gql/updateUserDisplayName.gql, dashboard/src/gql/app/settings/environmentVariables/getEnvironmentVariables.graphql, dashboard/src/pages/account/index.tsx, dashboard/src/utils/__generated__/graphql.ts
fixes https://github.com/nhost/nhost/issues/1489
=> feat: dashboard: add update user displayName section in account settings

.changeset/four-apes-push.md, .changeset/hip-clouds-hope.md, .changeset/shiny-doors-collect.md, dashboard/package.json, examples/codegen-react-apollo/package.json, examples/codegen-react-query/package.json, examples/codegen-react-urql/package.json, examples/react-apollo/package.json, examples/vue-apollo/src/pages/ProfilePage.vue, integrations/stripe-graphql-js/src/server.ts, packages/graphql-js/src/client.ts, pnpm-lock.yaml
fixes https://github.com/nhost/nhost/issues/2600
=> fix: graphql-js: resolve process is undefined error when running with vitejs

.changeset/flat-parrots-repair.md, packages/hasura-auth-js/package.json, pnpm-lock.yaml
fixes https://github.com/nhost/nhost/issues/2597
=> chore: hasura-auth-js: upgrade `@simplewebauthn/browser` to `9.0.1`

.changeset/fluffy-houses-doubt.md, dashboard/src/features/projects/common/components/ApplicationPaused/ApplicationPaused.tsx, dashboard/src/features/projects/common/components/ChangePlanModal/ChangePlanModal.tsx
fixes https://github.com/nhost/nhost/issues/2620
=> fix: await `unpauseApplication` promise

.changeset/poor-adults-unite.md, dashboard/src/pages/email/verify.tsx, dashboard/src/pages/signin/email.tsx, dashboard/src/pages/signup.tsx
resolves https://github.com/nhost/nhost/issues/2585
=> feat: dashboard: restrict signup/signin to verified emails only

.changeset/quick-boats-rhyme.md, dashboard/src/features/ai/AutoEmbeddingsForm/AutoEmbeddingsForm.tsx, dashboard/src/gql/graphite/auto-embeddings/getGraphiteAutoEmbeddingsConfigurations.gql, dashboard/src/gql/graphite/auto-embeddings/insertGraphiteAutoEmbeddingsConfiguration.gql, dashboard/src/gql/graphite/auto-embeddings/updateGraphiteAutoEmbeddingsConfiguration.gql, dashboard/src/utils/__generated__/graphite.graphql.ts, dashboard/src/utils/__generated__/graphql.ts
fixes https://github.com/nhost/nhost/issues/2660
=> feat: dashboard: add model field to auto-embeddings form

.changeset/clever-points-mate.md, packages/hasura-auth-js/src/internal-client.ts, packages/hasura-auth-js/src/machines/authentication/machine.ts
fixes https://github.com/nhost/nhost/issues/2635
=> fix: broadcast signout event to all tabs

.changeset/hip-years-film.md, examples/react-apollo/pnpm-lock.yaml, integrations/apollo/package.json, integrations/apollo/src/index.ts, packages/graphql-js/package.json, packages/graphql-js/src/client.ts, packages/hasura-auth-js/package.json, packages/hasura-auth-js/src/hasura-auth-client.ts, packages/react/package.json, packages/react/src/useDecodedAccessToken.ts, packages/vue/package.json, packages/vue/src/useDecodedAccessToken.ts, pnpm-lock.yaml
fixes https://github.com/nhost/nhost/issues/2603
=> fix: replace `jose` with `jwt-decode` version 4.0.0

.changeset/beige-lobsters-pay.md, dashboard/src/features/ai/settings/components/AISettings.tsx, dashboard/src/features/ai/settings/utils/isPostgresVersionValidForAI/index.ts, dashboard/src/features/ai/settings/utils/isPostgresVersionValidForAI/isPostgresVersionValidForAI.test.ts, dashboard/src/features/ai/settings/utils/isPostgresVersionValidForAI/isPostgresVersionValidForAI.ts
=> fix (dashboard): validate postgres version in ai service settings page

.changeset/selfish-crabs-carry.md, docs/guides/functions/runtimes.mdx, docs/mint.json, docs/product/functions.mdx
Documentation
___
- Added new documentation for supported runtimes and package managers, including configuration examples for Node.js 18 and Node.js 20.
- Updated `mint.json` to include the new runtimes documentation page.
- Added a card link to the new runtimes documentation in the functions overview.
- Included changeset information for the new documentation feature.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>selfish-crabs-carry.md</strong><dd><code>Add changeset for runtime and package manager documentation</code></dd></summary>
<hr>
.changeset/selfish-crabs-carry.md
- Added changeset information for the new documentation feature.
</details>
</td> …
=> feat (docs): functions: added runtime/pkg manager information

.changeset/metal-bears-tease.md, dashboard/src/features/projects/overview/components/OverviewProjectHealth/OverviewProjectHealth.tsx
Changes title from 'Service logs' to 'Service State'
___
___
- Changed the modal title in the project health overview from 'Service logs' to 'Service State'.
- Added a changeset to document the update of the title text on the service status modal.
___
<tr>
<td>
<details>
<summary><strong>OverviewProjectHealth.tsx</strong><dd><code>Update modal title in project health overview</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/features/projects/overview/components/OverviewProjectHealth/OverviewProjectHealth.tsx
- Changed the modal title from 'Service logs' …
=> dashboard: chore: project health change modal title

.changeset/shy-timers-turn.md, docs/reference/react-native/support.mdx
Documentation
___
- Fixed a broken link in the React Native support documentation.
- Added a changeset file to document the fix.
___
<tr>
<td>
<details>
<summary><strong>shy-timers-turn.md</strong><dd><code>Add changeset for documentation update</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.changeset/shy-timers-turn.md
- Added a changeset file for documenting the fix.
</details>
</td>
<td><a href="https://github.com/nhost/nhost/pull/2769/files#diff-aa1aee3c26ad3629dfa2b0d08f8bd549fae09ea5b61c8ff846d3fc38d82bd884">+5/-0</a>&nbsp; &nbsp; …
=> chore(docs): fix broken link in react-native reference

.changeset/nice-pandas-double.md, dashboard/src/utils/execPromiseWithErrorToast/execPromiseWithErrorToast.tsx
=> dashboard: fix: close error toasts individually

dashboard/src/components/ui/v2/ErrorToast/ErrorToast.test.tsx, dashboard/src/components/ui/v2/ErrorToast/ErrorToast.tsx
=> dashboard: chore: error toast message improvements

.github/actions/install-dependencies/action.yaml, package.json
enhancement, configuration changes
___
- Updated `pnpm/action-setup` to version 4 in GitHub Actions configuration.
- Updated `packageManager` to `pnpm@8.10.5` in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>action.yaml</strong><dd><code>Update pnpm/action-setup to v4 in GitHub Actions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/actions/install-dependencies/action.yaml
<li>Updated <code>pnpm/action-setup</code> version to v4.<br> <li> Set <code>pnpm</code> version to 8.10.5.<br>
</details>
</td>
<td><a href="https://github.com/nhost/nhost/pull/2784/files#diff-342d59190b4737ee45e2062 …
=> chore: update pnpm/action-setup to v4

.changeset/six-ways-call.md, dashboard/src/components/form/CountrySelector/CountrySelector.tsx, dashboard/src/features/ai/AssistantForm/components/ArgumentsFormSection/ArgumentsFormSection.tsx, dashboard/src/features/services/components/ServiceForm/components/PortsFormSection/PortsFormSection.tsx
=> fix (dashboard): align dropdown items in select component

.changeset/tame-apples-give.md, dashboard/src/pages/new.tsx
=> fix (dashboard): show city name in region selector for project creation

.changeset/gentle-brooms-flash.md, examples/react-apollo/e2e/authenticated/change-email.test.ts, examples/react-apollo/e2e/utils.ts, examples/react-apollo/nhost/nhost.toml, examples/react-apollo/src/Verify.tsx
fixes https://github.com/nhost/nhost/issues/2741
___
Bug fix, Enhancement, Tests
___
- Added a `requestType` parameter to the `verifyEmail` function to handle different types of email verification requests.
- Updated the email change test to include the `requestType` parameter.
- Replaced auto-redirect in the `VerifyPage` component with a verification button and added error handling with notifications.
- Updated dependencies in `nhost.toml` to newer versions.
- Added a changeset file to document the email verification button update.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>change-email.test.ts</strong><dd><code>Update email change test with request type …
=> fix(react-apollo): add verify email button

.changeset/stale-rocks-work.md, dashboard/src/components/layout/SettingsLayout/SettingsLayout.tsx, dashboard/src/features/projects/common/components/settings/TOMLEditor/TOMLEditor.tsx
=> fix (dashboard): don't show double scrollbar in configuration editor

.changeset/small-trees-approve.md, packages/hasura-auth-js/src/machines/authentication/machine.ts
fixes https://github.com/nhost/nhost/issues/2763
related https://github.com/nhost/nhost/issues/2635
___
___
- Refactored the `refreshTimer` logic in `createAuthMachine` to avoid an infinite loop when the `refreshToken` has expired.
- Moved the condition checking if `expiresAt` is less than the current time to ensure proper token refresh handling.
- Added a changeset file to document the patch update.
___
<tr>
<td>
<details>
<summary><strong>machine.ts</strong><dd><code>Refactor refreshTimer logic to prevent infinite loop</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> fix(hasura-auth-js): refactor refreshTimer logic to avoid an infinite loop when refreshToken has expired

.changeset/nasty-fishes-remain.md, dashboard/public/assets/LockedApp.svg, dashboard/src/components/ui/v2/createTheme/createTheme.ts, dashboard/src/components/ui/v2/icons/PowerOffIcon/PowerOffIcon.tsx, dashboard/src/components/ui/v2/icons/PowerOffIcon/index.ts, dashboard/src/components/ui/v2/theme/getDesignTokens/getDesignTokens.ts, dashboard/src/features/projects/common/components/ApplicationLockedReason/ApplicationLockedReason.tsx, dashboard/src/features/projects/common/components/ApplicationLockedReason/index.ts, dashboard/src/features/projects/common/components/ApplicationPaused/ApplicationPaused.tsx, dashboard/src/features/projects/common/components/ApplicationPausedReason/ApplicationPausedReason.tsx, dashboard/src/features/projects/common/components/ApplicationPausedReason/index.ts, dashboard/src/features/projects/common/components/ApplicationPausedSymbol/ApplicationPausedSymbol.tsx, dashboard/src/features/projects/common/components/ApplicationPausedSymbol/index.ts, dashboard/src/features/projects/common/hooks/useAppPausedReason/index.ts, dashboard/src/features/projects/common/hooks/useAppPausedReason/useAppPausedReason.ts, dashboard/src/gql/app/getProjectIsLocked.graphql, dashboard/src/utils/__generated__/graphql.ts
=> feat (dashboard): show contact us info when project is locked

.changeset/warm-bulldogs-search.md, dashboard/src/features/database/dataGrid/components/ColumnAutocomplete/ColumnAutocomplete.tsx
=> dashboard: fix: type custom row permissions autocomplete

audit-ci.jsonc
enhancement
___
- Added `vue-template-compiler` to the `allowlist` in `audit-ci.jsonc` to address vulnerabilities.
___
<tr>
<td>
<details>
<summary><strong>audit-ci.jsonc</strong><dd><code>Add `vue-template-compiler` to audit-ci allowlist</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
audit-ci.jsonc
- Added `vue-template-compiler` to the `allowlist` array.
</details>
</td>
<td><a href="https://github.com/nhost/nhost/pull/2810/files#diff-4ede69da2a1704e53e08b8d647a315c202f037cc9277f16c94176d9622d261c6">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>
___
> 💡 …
=> chore: add "vue-template-compiler" to allowlist in audit-ci.jsonc

.changeset/five-avocados-complain.md, .changeset/orange-pears-hug.md, docs/reference/javascript/auth/types/nhost-auth-constructor-params.mdx, docs/reference/javascript/nhost-js/types/auth-options.mdx, docs/reference/nextjs/types/nhost-react-client-constructor-params.mdx, docs/reference/react/types/nhost-react-client-constructor-params.mdx, docs/reference/vue/types/nhost-vue-client-constructor-params.mdx, packages/hasura-auth-js/src/types/client.ts
closes https://github.com/nhost/nhost/issues/2237
___
Documentation
___
- Enhanced `clientStorage` documentation across multiple files with detailed usage examples.
- Added specific instructions for Capacitor versions < 4 and >= 4.
- Included new documentation file for `AuthOptions`.
- Added changesets for documentation updates.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><details><summary>9 files</summary><table>
<tr>
<td>
<details>
<summary><strong>client.ts</strong><dd><code>Enhanced `clientStorage` documentation with usage examples</code></dd></summary>
<hr>
packages/hasura-auth-js/src/types/client.ts
<li>Added detailed usage examples for different <code>clientStorageType</code> values.<br> <li> …
=> chore: update `clientStorage` documentation for Capacitor and add usage examples

.changeset/gorgeous-peaches-matter.md, dashboard/src/features/projects/common/components/ChangePlanModal/ChangePlanModal.tsx, dashboard/src/features/projects/common/utils/planDescriptions/planDescriptions.ts
=> chore (dashboard): update pricing information

.changeset/nasty-vans-talk.md, dashboard/src/features/services/components/ServiceForm/components/ServiceConfirmationDialog/ServiceConfirmationDialog.tsx
=> fix (dashboard): not allow run service creation form resubmission while creating a run service

.changeset/gold-schools-destroy.md, dashboard/e2e/auth/ban-user.test.ts, dashboard/e2e/auth/create-user.test.ts, dashboard/e2e/auth/delete-user.test.ts, dashboard/e2e/auth/verify-user.test.ts, dashboard/e2e/database/create-table.test.ts, dashboard/e2e/database/delete-table.test.ts, dashboard/e2e/run/run.test.ts, dashboard/playwright.config.ts, dashboard/src/features/services/components/ServicesList/ServicesList.tsx
___
- Fixed the button selector in the end-to-end test for deleting a service, ensuring the correct button is targeted.
- Refactored the `ServicesList` component to standardize icon sizes and improve the order of class attributes for better readability.
- Added event stop propagation to the delete service action to prevent unintended event bubbling.
___
<tr>
<td>
<details>
<summary><strong>run.test.ts</strong><dd><code>Fix button selector in e2e test for service deletion</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/e2e/run/run.test.ts
<li>Updated button selector for deleting a service.<br> <li> Removed …
=> fix(e2e): fix run service e2e test

.changeset/fair-chicken-deliver.md, dashboard/src/features/graphql/common/components/UserSelect/UserSelect.tsx, dashboard/src/features/graphql/common/hooks/index.ts, dashboard/src/features/graphql/common/hooks/useGetAppUsers.ts
=> feat (dashboard): allow filtering users in "make request as" feature of graphql section

.changeset/lucky-mirrors-relate.md, examples/react-apollo/src/components/profile/security-keys.tsx
Enhancement, Bug fix
___
- Enhanced security key management by adding elevated permission checks:
- Implemented `elevatePermission` function to centralize permission elevation logic
- Added permission check before deleting a security key
- Modified `onSubmit` function to use `elevatePermission` before adding a key
- Refactored code structure for improved readability and maintainability:
- Moved `removeKey` mutation definition earlier in the component
- Simplified conditional logic in `onSubmit` function
- Added a changeset file to document the bug fix for elevated permission check
___
<tr>
<td>
<details> …
=> fix(react-apollo): add elevated permission check before deleting a security key

dashboard/package.json, dashboard/src/pages/signup.tsx, pnpm-lock.yaml
Enhancement
___
- Integrated Cloudflare Turnstile for enhanced signup verification:
- Added Turnstile component to the signup form
- Implemented state management for Turnstile response
- Modified form submission to include Turnstile response in headers
- Added error handling to prevent form submission without Turnstile verification
- Updated package.json to include @marsidev/react-turnstile as a dependency
- Refactored code to improve readability and maintainability
___
<tr>
<td>
<details>
<summary><strong>signup.tsx</strong><dd><code>Integrate Cloudflare Turnstile for Signup Verification</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> feat(dashboard): feat: integrate Cloudflare Turnstile for signup verification

.changeset/breezy-fans-kiss.md, docs/guides/run/networking.mdx, docs/mint.json, docs/platform/tls.mdx
___
- Added a new comprehensive guide on advanced TLS configuration, including TLS Client Authentication
- Updated the networking guide to include GRPC support and configuration
- Added a new 'platform/tls' page to the documentation structure
- Included a detailed step-by-step guide for setting up TLS Client Authentication
- Provided examples of TLS configuration and usage with curl commands
- Updated the list of supported service types to include 'grpc'
___
<tr>
<td>
<details>
<summary><strong>breezy-fans-kiss.md</strong><dd><code>Add changeset for TLS documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> feat (docs): added advanced TLS document

.changeset/brown-bulldogs-help.md, docs/guides/database/extensions.mdx
Documentation, Enhancement
___
- Added documentation for the PostgreSQL ip4r extension in the database guide
- Included instructions for installing and uninstalling the ip4r extension
- Added a link to the ip4r GitHub repository for further reference
- Created a new changeset file to track the documentation update
___
<tr>
<td>
<details>
<summary><strong>brown-bulldogs-help.md</strong><dd><code>Add changeset for ip4r extension documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.changeset/brown-bulldogs-help.md
<li>Added a new changeset file for documenting the addition of ip4r …
=> chore (docs): added pg's ip4r extension documentation

.changeset/perfect-apricots-smash.md, dashboard/src/features/hasura/settings/gql/getHasuraSettings.gql, dashboard/src/features/orgs/projects/hasura/settings/components/HasuraInferFunctionPermissionsSettings/HasuraInferFunctionPermissionsSettings.tsx, dashboard/src/features/orgs/projects/hasura/settings/components/HasuraInferFunctionPermissionsSettings/index.ts, dashboard/src/features/orgs/projects/hasura/settings/gql/getHasuraSettings.gql, dashboard/src/pages/orgs/[orgSlug]/projects/[appSlug]/settings/hasura.tsx, dashboard/src/utils/__generated__/graphql.ts
Resolves #2867
___
Enhancement
___
- Added a new HasuraInferFunctionPermissionsSettings component to manage the Infer Function Permissions setting for Hasura.
- Integrated the new component into the Hasura settings page.
- Updated GraphQL types and queries to include the inferFunctionPermissions field.
- Added necessary exports and imports for the new component.
- Created a changeset to document the new feature.
- Updated GetHasuraSettings queries in multiple locations to include the new field.
- Removed unused types related to organizations_free_usage.
___
<tr>
<td>
<details>
<summary><strong>HasuraInferFunctionPermissionsSettings.tsx</strong><dd><code>Ad …
=> feat (dashboard): add hasura infer function permissions setting

.changeset/hungry-penguins-occur.md, dashboard/src/features/hasura/settings/components/HasuraInferFunctionPermissionsSettings/HasuraInferFunctionPermissionsSettings.tsx, dashboard/src/features/hasura/settings/components/HasuraInferFunctionPermissionsSettings/index.ts, dashboard/src/pages/[workspaceSlug]/[appSlug]/settings/hasura/index.tsx
Enhancement
___
- Implemented a new HasuraInferFunctionPermissionsSettings component to manage Hasura's infer function permissions setting
- Added the new component to the Hasura settings page in the dashboard
- Integrated the feature with both platform and local environments
- Included form handling, validation, and API integration for updating the setting
- Added error handling, loading states, and maintenance mode support
- Created a changeset to document the feature addition and specify a minor version bump
___
<tr>
<td>
<details>
<summary><strong>HasuraInferFunctionPermissionsSettings.tsx</strong><dd><code>Implement …
=> feat (dashboard): add hasura infer function permissions setting to legacy workspaces

.changeset/quiet-geckos-juggle.md, docs/guides/auth/social/sign-in-azuread.mdx, docs/mint.json
___
- Added a comprehensive guide for signing in with Azure AD (Azure Active Directory)
- Provided detailed instructions for setting up Azure AD in the Azure Portal
- Explained the process of configuring Nhost to work with Azure AD
- Included a code snippet demonstrating how to implement Azure AD sign-in using the Nhost JavaScript client
- Updated the documentation navigation to include the new Azure AD guide
- Created a changeset to document the addition of the Azure AD guide and specify a minor version bump
___
<tr>
<td>
<details>
<summary><strong>quiet-geckos-juggle.md</strong><dd><code>Add changeset for Azure AD …
=> feat (docs): added azuread's guide

dashboard/src/features/orgs/components/OrgStatus/OrgStatus.tsx
Enhancement
___
- Improved organization status messages for better clarity and user guidance:
- Updated messages for AllowanceExceeded, Cancelled, Disabled, and Locked states
- Added more specific information about the consequences of each state
- Enhanced UI for status banners:
- Added rounded corners and margin
- Improved layout and styling
- Increased flexibility of the StatusBanner component:
- Changed `description` prop type from `string` to `React.ReactNode`
- Allows for rich content, such as links, in status messages
- Added a direct link to the support ticket system in the 'Cancelled' status message
- Imported and used Next.js Link component for internal navigation
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</st …
=> feat: dashboard: orgs states messaging

dashboard/src/components/common/UpgradeToProBanner/UpgradeToProBanner.tsx, dashboard/src/features/orgs/projects/resources/settings/components/ResourcesConfirmationDialog/ResourcesConfirmationDialog.tsx, dashboard/src/features/orgs/projects/resources/settings/components/ResourcesForm/ResourcesForm.tsx, dashboard/src/features/orgs/projects/resources/settings/components/ResourcesForm/ResourcesFormFooter.tsx, dashboard/src/features/orgs/projects/resources/settings/components/TotalResourcesFormFragment/TotalResourcesFormFragment.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSlug]/ai/assistants/index.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSlug]/ai/auto-embeddings/index.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSlug]/backups.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSlug]/metrics.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSlug]/run.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSlug]/settings/ai.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSlug]/settings/compute-resources.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSlug]/settings/custom-domains.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSlug]/settings/smtp.tsx
Enhancement
___
- Refactored UpgradeToProBanner component to focus on project transfer instead of plan upgrade
- Updated pricing calculations across various components to exclude Pro Plan price
- Replaced UpgradeNotification with UpgradeToProBanner across multiple pages
- Updated messaging for unlocking features to emphasize transferring to Pro or Team organization
- Adjusted UI elements and styling in various components to reflect the new upgrade flow
- Removed references to ChangePlanModal and related components
- Added TransferProjectDialog to UpgradeToProBanner component
- Updated descriptions and labels to reflect the new pricing and upgrade model
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><detail …
=> feat: orgs: upgrade -> migrate

dashboard/src/pages/support/index.tsx
Bug fix
___
- Fixed the size of the `Logo` component in the support page to ensure proper display.
___
<tr>
<td>
<details>
<summary><strong>index.tsx</strong><dd><code>Fix logo size in support page</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/pages/support/index.tsx
- Adjusted the size of the `Logo` component.
</details>
</td>
<td><a href="https://github.com/nhost/nhost/pull/2936/files#diff-64adb32f73092cbba8aedac54225398c237222d9ba03a702bbe9d676edcde49c">+1/-1</a>&nbsp; …
=> fix support page

dashboard/src/components/layout/AuthenticatedLayout/AuthenticatedLayout.tsx, dashboard/src/features/projects/common/hooks/useNotFoundRedirect/useNotFoundRedirect.ts, dashboard/src/pages/support/ticket.tsx
___
- Refactored class names in `AuthenticatedLayout` component for better readability and consistency.
- Added `/support/ticket` to the list of paths that should not redirect to 404 in `useNotFoundRedirect` hook.
- Refactored class names in the support ticket page for better readability and consistency.
___
<tr>
<td>
<details>
<summary><strong>AuthenticatedLayout.tsx</strong><dd><code>Refactor class names in AuthenticatedLayout component</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/components/layout/AuthenticatedLayout/AuthenticatedLayout.tsx
<li>Adjusted class names for better readability and consistency.<br> …
=> fix create support ticket page

dashboard/src/pages/[workspaceSlug]/[appSlug]/graphql.tsx
Bug fix
___
- Fixed the layout issue in the GraphiQL page by ensuring the main container takes the full height.
- Reordered some CSS class attributes for better readability and maintainability.
___
<tr>
<td>
<details>
<summary><strong>graphql.tsx</strong><dd><code>Fix layout issues in GraphiQL page</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/pages/[workspaceSlug]/[appSlug]/graphql.tsx
<li>Adjusted CSS classes to ensure full height for the main container.<br> <li> Minor reordering of CSS class attributes …
=> fix: graphiql layout on workspaces

.changeset/eighty-flowers-explain.md, .github/workflows/changesets.yaml, dashboard/src/features/orgs/components/MigrateProjectToOrg/MigrateProjectToOrg.tsx, dashboard/src/features/orgs/projects/git/common/components/EditRepositorySettingsModal/EditRepositorySettingsModal.tsx, dashboard/src/features/orgs/projects/git/settings/components/GitConnectionSettings/GitConnectionSettings.tsx, dashboard/src/features/orgs/projects/overview/components/OverviewRepository/OverviewRepository.tsx, dashboard/src/features/orgs/projects/resources/settings/components/ResourcesForm/ResourcesForm.test.tsx
___
- Corrected displayed price values in multiple test cases within `ResourcesForm.test.tsx`.
- Adjusted expected text content in assertions to match the corrected price values.
- Added a dependency on the test job for the Vercel publishing job in the GitHub Actions workflow.
___
<tr>
<td>
<details>
<summary><strong>ResourcesForm.test.tsx</strong><dd><code>Fix displayed price values in resource form tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/features/orgs/projects/resources/settings/components/ResourcesForm/ResourcesForm.test.tsx
<li>Corrected displayed price values in multiple …
=> fix: compute resources form unit tests

.changeset/dry-dancers-mate.md, dashboard/src/features/orgs/projects/overview/components/OverviewRepository/OverviewRepository.tsx
Bug fix, Other
___
- Fixed an incorrect path in the project settings navigation within the `OverviewRepository` component.
- Added a changeset file to document the bug fix.
___
PRDescriptionHeader.CHANGES_WALKTHROUGH
<tr>
<td>
<details>
<summary><strong>OverviewRepository.tsx</strong><dd><code>Fix incorrect path in project settings navigation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/features/orgs/projects/overview/components/OverviewRepository/OverviewRepository.tsx
<li>Fixed incorrect path in project settings navigation.<br> <li> Updated <code>href</code> attribute in <code>NavLink</code>.<br> …
=> fix: overview deployments

dashboard/src/pages/support/ticket.tsx
___
- Fixed import order to comply with linter rules in `ticket.tsx`.
- Refactored logic to get available projects into a `getAvailableProjects` function for better readability and maintainability.
- Improved readability by reordering JSX attributes and fixing minor formatting issues.
___
PRDescriptionHeader.CHANGES_WALKTHROUGH
<tr>
<td>
<details>
<summary><strong>ticket.tsx</strong><dd><code>Fix linter errors and refactor project selection logic</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/pages/support/ticket.tsx
<li>Fixed import order to comply with linter rules.<br> <li> Refactored logic to get available projects …
=> chore: fix linter errors

.changeset/neat-dragons-cough.md, dashboard/src/features/orgs/components/ui/v2/ErrorToast/ErrorToast.tsx
Missing changes in organizations from PR https://github.com/nhost/nhost/pull/2892
=> fix (dashboard): long error message in orgs error toast overflow

.changeset/nervous-islands-fetch.md, dashboard/src/features/orgs/projects/services/components/ServiceForm/components/ComputeFormSection/ComputeFormSection.tsx, dashboard/src/features/orgs/projects/services/components/ServiceForm/components/StorageFormSection/StorageFormSection.tsx, dashboard/src/features/services/components/ServiceForm/components/ComputeFormSection/ComputeFormSection.tsx, dashboard/src/features/services/components/ServiceForm/components/StorageFormSection/StorageFormSection.tsx
Add missing changes from PR https://github.com/nhost/nhost/pull/2886
=> fix (dashboard): update urls to documentation in run services tooltips

.changeset/popular-rings-retire.md, dashboard/src/features/authentication/settings/components/DisableNewUsersSettings/DisableNewUsersSettings.tsx, dashboard/src/features/authentication/settings/gql/getAuthenticationSettings.gql, dashboard/src/features/orgs/projects/authentication/settings/components/DisableNewUsersSettings/DisableNewUsersSettings.tsx, dashboard/src/features/orgs/projects/authentication/settings/components/DisableSignUpsSettings/DisableSignUpsSettings.tsx, dashboard/src/features/orgs/projects/authentication/settings/components/DisableSignUpsSettings/index.ts, dashboard/src/features/orgs/projects/authentication/settings/gql/getAuthenticationSettings.gql, dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/settings/authentication.tsx, dashboard/src/utils/__generated__/graphql.ts
=> fix (dashboard): configuring "Disable New Users" modifies the wrong setting

docs/guides/database/performance.mdx
chore: docs: fix ✅  broken links 🔗 on database performance guide
=> chore: docs: fix ✅  broken links 🔗 on database performance guide

.changeset/bright-actors-camp.md
documentation
___
- Added a changeset file to document the minor updates for audience, OTP, and JWT settings in the `@nhost/dashboard` package.
___
<tr>
<td>
<details>
<summary><strong>bright-actors-camp.md</strong><dd><code>Add changeset for audience, OTP, and JWT settings</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.changeset/bright-actors-camp.md
- Added a changeset file for audience, OTP, and JWT settings.
</details>
</td>
<td><a href="https://github.com/nhost/nhost/pull/3029/files#diff-a4dfd9e2b40b9a6675dc27e906be963c76ceaa196da7ee32072d3adf6d73a9fe">+5/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
=> chore: add changeset for audience, otp and jwt settings

.changeset/three-squids-march.md, docs/guides/database/extensions.mdx
Documentation
___
- Added a comprehensive overview section listing available PostgreSQL extensions in a table format.
- Included detailed documentation for the `pg_repack` extension, including its purpose, installation, and uninstallation instructions.
- Updated the changeset to reflect the minor documentation fix.
___
<tr>
<td>
<details>
<summary><strong>three-squids-march.md</strong><dd><code>Added changeset for documentation updates</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.changeset/three-squids-march.md
<li>Added changeset file for documentation …
=> fix (docs): added pg_repack and an extension overview to database guide

.github/workflows/deploy-dashboard.yaml
enhancement, configuration changes
___
- Added a new GitHub Actions workflow (`deploy-dashboard.yaml`) to automate the deployment of the dashboard.
- The workflow supports deployment to different environments: staging, production, and all.
- Configured steps include checking out the repository, installing Node and dependencies, setting up Vercel CLI, and triggering the deployment based on the selected environment.
___
<tr>
<td>
<details>
<summary><strong>deploy-dashboard.yaml</strong><dd><code>Introduce deploy-dashboard workflow with environment options</code></dd></summary>
<hr>
.github/workflows/deploy-dashboard.yaml
<li>Added a new GitHub …
=> chore(ci): add deploy-dashboard workflow with environment options

docs/guides/auth/email-templates.mdx, docs/guides/cli/subdomain.mdx
Documentation
___
- Added a new email template section for `signin-otp` in the authentication guide.
- Updated the description of the `ticket` variable to include OTP authorization.
- Corrected a typo in the CLI subdomain guide regarding dynamic DNS usage.
- Introduced a warning about potential ISP filtering of DNS responses and provided solutions.
___
<tr>
<td>
<details>
<summary><strong>email-templates.mdx</strong><dd><code>Add `signin-otp` email template and update variable description</code></dd></summary>
<hr>
docs/guides/auth/email-templates.mdx
<li>Added new email template section for <code>signin-otp</code>.<br> <li> Updated description for …
=> docs (chore): various minor improvements

.changeset/purple-pumas-smash.md, dashboard/src/components/layout/Header/ProjectsComboBox.tsx, dashboard/src/features/orgs/components/common/ProjectStatusIndicator/ProjectStatusIndicator.tsx, dashboard/src/features/orgs/components/common/ProjectStatusIndicator/index.ts, dashboard/src/features/orgs/components/projects/projects-grid/projects-grid.tsx, dashboard/src/features/orgs/projects/deployments/components/DeploymentStatusMessage/DeploymentStatusMessage.test.tsx, dashboard/src/features/orgs/projects/deployments/components/DeploymentStatusMessage/DeploymentStatusMessage.tsx, dashboard/src/gql/organizations/getProjects.gql, dashboard/src/utils/__generated__/graphql.ts
fixes https://github.com/nhost/nhost/issues/2995
___
Enhancement, Tests
___
- Refactored the `ProjectsComboBox` to use an external `ProjectStatusIndicator` component, improving code modularity.
- Introduced a new `ProjectStatusIndicator` component to visually represent project statuses with hover descriptions.
- Enhanced the project grid layout by integrating status indicators and adjusting the grid configuration for better display.
- Updated `DeploymentStatusMessage` component and its tests to simplify the props and improve status message handling.
- Extended GraphQL queries and types to include additional project details such as region and application states.
- Added a changeset to document the improvements made to the project grid.
___
<table><thead><tr><th></th><th …
=> feat(dashboard): improve projects grid

.changeset/late-shrimps-taste.md, docs/reference/javascript/auth/refresh-session.mdx, packages/hasura-auth-js/src/hasura-auth-client.ts
documentation, enhancement
___
- Corrected the function name from `refreshToken` to `refreshSession` in both TypeScript code and documentation.
- Updated code examples and documentation to reflect the correct function usage.
- Added a changeset to document the changes made to the function name.
___
<tr>
<td>
<details>
<summary><strong>hasura-auth-client.ts</strong><dd><code>Correct function name in TypeScript code examples</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/hasura-auth-js/src/hasura-auth-client.ts
<li>Corrected function name from <code>refreshToken</code> to <code>refreshSession</code> in code …
=> chore: fix docs

.changeset/thin-pants-battle.md, dashboard/src/components/common/SelectOrg/SelectOrg.tsx, dashboard/src/components/common/SelectOrg/index.ts, dashboard/src/components/common/SelectOrgAndProject/SelectOrgAndProject.tsx, dashboard/src/components/common/SelectOrgAndProject/index.ts, dashboard/src/features/projects/common/hooks/useNotFoundRedirect/useNotFoundRedirect.ts, dashboard/src/pages/orgs/_/[...slug].tsx, dashboard/src/pages/orgs/_/projects/_/[...slug].tsx, dashboard/src/pages/orgs/_/projects/_/index.tsx
enhancement
___
- Introduced new components `SelectOrg` and `SelectOrgAndProject` for selecting organizations and projects, respectively.
- Implemented filtering functionality for both organizations and projects.
- Integrated loading indicators and error boundaries for better user experience.
- Added navigation logic to handle routing to selected organization and project pages.
- Updated redirect logic to accommodate new routes for organizations and projects.
- Added new pages and index for organization and project selection.
- Documented changes in a changeset file.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td>
<details> …
=> feat: dashboard: add org and project static placeholder routes

.changeset/stale-avocados-shake.md, dashboard/src/features/orgs/layout/ProjectLayout/ProjectLayout.tsx, dashboard/src/features/orgs/projects/common/hooks/useAppState/useAppState.ts, dashboard/src/features/orgs/projects/hooks/useProject/useProject.ts, dashboard/src/features/orgs/projects/hooks/useProjectWithState/index.ts, dashboard/src/features/orgs/projects/hooks/useProjectWithState/useProjectWithState.ts, dashboard/src/gql/organizations/getProjectState.gql, dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/ai/auto-embeddings/index.tsx, dashboard/src/utils/__generated__/graphql.ts
Enhancement, Other
___
- Introduced a new hook `useProjectWithState` to improve project state polling, replacing the previous `useProject` hook.
- Updated components and hooks to use `useProjectWithState` for better performance and state management.
- Enhanced GraphQL schema with new queries and types, including virus management capabilities.
- Removed deprecated fields and functions from the GraphQL schema.
___
<tr>
<td>
<details>
<summary><strong>ProjectLayout.tsx</strong><dd><code>Update project hook to improve state polling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> feat: split get project query to improve performance while polling for the project state

.changeset/silver-goats-stare.md, dashboard/package.json, dashboard/src/components/layout/AuthenticatedLayout/AuthenticatedLayout.tsx, dashboard/src/pages/[workspaceSlug]/[appSlug]/users/index.tsx, dashboard/src/pages/index.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/users.tsx, dashboard/src/pages/support/ticket.tsx
enhancement, bug fix
___
- Removed unused `contentContainerProps` from various layout components to simplify the code.
- Refactored class names across multiple files for better readability and consistency.
- Disabled duplicate atom key checking in development mode to improve performance.
- Added a changeset for the layout cleanup and configuration changes.
___
<tr>
<td>
<details>
<summary><strong>AuthenticatedLayout.tsx</strong><dd><code>Remove unused props and clean imports in AuthenticatedLayout</code></dd></summary>
<hr>
dashboard/src/components/layout/AuthenticatedLayout/AuthenticatedLayout.tsx
<li>Removed unused <code>contentContainerProps</code> …
=> chore(dashboard): cleanup layout and add disable duplicate atom key checking in development mode

.changeset/wicked-colts-fetch.md, docs/guides/quickstarts/nextjs.mdx, docs/guides/quickstarts/react-native.mdx, docs/guides/quickstarts/react.mdx, docs/guides/quickstarts/vue.mdx, docs/guides/tutorials/nextjs.mdx, docs/guides/tutorials/react.mdx, docs/guides/tutorials/vue.mdx
Bug fix, Documentation
___
- Fixed broken links to create a new project in the Nhost Dashboard across multiple documentation files
- Updated the URL from `https://app.nhost.io/new` to `https://app.nhost.io` in all affected files
- Modified quickstart guides for Next.js, React Native, React, and Vue
- Updated tutorial guides for Next.js, React, and Vue
- Added a changeset file to document the fix and specify the version change for `@nhost/docs`
___
<tr>
<td>
<details>
<summary><strong>wicked-colts-fetch.md</strong><dd><code>Add changeset for documentation update</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix (docs): broken links to create new project in dashboard

.changeset/smooth-wombats-begin.md, packages/hasura-storage-js/src/hasura-storage-client.ts
Fixes #2964
___
Bug fix
___
- Fixed a critical bug in the `HasuraStorageClient` class where the `getHeaders` method was causing a stack overflow due to recursive self-calling.
- Updated the `getHeaders` method to correctly call `this.api.getHeaders()` instead of `this.getHeaders()`.
- Added a changeset file to document the bug fix and specify a minor version bump for the '@nhost/hasura-storage-js' package.
- This fix resolves the issue reported in ticket #2964, where calling `nhostClient.storage.getHeaders()` was leading to a stack overflow error.
___
<tr>
<td>
<details>
<summary><strong>hasura-storage-client.ts</strong><dd><code>Fix stack overflow in storage …
=> fix (hasura-storage-js): stack overflow on storage client getHeaders

.changeset/tidy-camels-complain.md, dashboard/src/components/layout/UnauthenticatedLayout/UnauthenticatedLayout.tsx, dashboard/src/pages/password/new.tsx, dashboard/src/pages/password/reset.tsx, dashboard/src/pages/signin/email.tsx
resolves https://github.com/nhost/nhost/issues/3058
___
Enhancement, Bug fix
___
- Renamed the existing reset password page to `NewPasswordPage` and updated its form handling.
- Added a new `ResetPasswordPage` with a form to change the password, including validation and success/error handling.
- Updated the "Forgot password?" link in the sign-in page to direct users to the new password page.
___
<tr>
<td>
<details>
<summary><strong>new.tsx</strong><dd><code>Rename and update reset password page</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
=> feat(dashboard): add change password form

.changeset/forty-knives-check.md, dashboard/src/features/orgs/projects/authentication/users/components/EditUserForm/EditUserForm.tsx, dashboard/src/features/orgs/projects/authentication/users/components/UsersBody/UsersBody.tsx
Fixes #2472
___
Bug fix
___
- Fixed issue with user roles not appearing locally in the Nhost dashboard
- Implemented support for fetching user roles and locales using a local Mimir client when not running on the Nhost platform
- Modified queries in EditUserForm and UsersBody components to use the local client when appropriate
- Corrected image source paths for provider logos in both components
- Added a changeset file to document the minor version bump and fix description
- Improved code formatting and consistency
___
<tr>
<td>
<details>
<summary><strong>EditUserForm.tsx</strong><dd><code>Add local client support for user roles and locales</code>&nbsp; …
=> fix (dashboard): fetch user roles locally in auth section

.github/actions/install-dependencies/action.yaml
Enhancement
___
- Update actions/cache from v3 to v4
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>action.yaml</strong><dd><code>Update actions/cache version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/actions/install-dependencies/action.yaml
- Upgraded actions/cache from v3 to v4
</details>
</td>
<td><a href="https://github.com/nhost/nhost/pull/3120/files#diff-342d59190b4737ee45e2062eb625ada477bcea5b4a843b25900ad55d7982f200">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
=> chore: update actions/cache to v4

.changeset/nice-mangos-act.md, dashboard/src/features/orgs/projects/database/dataGrid/components/DataBrowserGrid/DataBrowserGrid.tsx, dashboard/src/features/orgs/projects/database/dataGrid/components/DatabaseRecordInputGroup/DatabaseRecordInputGroup.tsx, dashboard/src/features/orgs/projects/database/dataGrid/utils/postgresqlConstants/postgresqlConstants.ts, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridDecimalCell/DataGridDecimalCell.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridDecimalCell/index.ts, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridIntegerCell/DataGridIntegerCell.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridIntegerCell/index.ts, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridNumericCell/DataGridNumericCell.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridNumericCell/index.ts
Fixes #2923
___
___
- Allow decimal numbers in database row insert
- Separate integer and decimal cell components
- Update PostgreSQL type constants
- Refactor DataBrowserGrid component imports
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>7 files</summary><table>
<tr>
<td><strong>DataBrowserGrid.tsx</strong><dd><code>Refactor imports and add decimal cell support</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a href="https://github.com/nhost/nhost/pull/3110/files#diff-5910fd8730fbe65c60aa5f54031989a7868e944d5958f69535e5684b72ca1396">+22/-11</a>&nbsp; </td>
</tr>
<tr> …
=> fix (dashboard): allow decimal row insert

.changeset/curly-hotels-hang.md, dashboard/src/features/orgs/projects/services/components/ServiceForm/ServiceForm.tsx, dashboard/src/features/orgs/projects/services/components/ServiceForm/ServiceFormTypes.ts, dashboard/src/features/orgs/projects/services/components/ServiceForm/components/ReplicasFormSection/ReplicasFormSection.tsx, dashboard/src/features/services/components/ServiceForm/ServiceForm.tsx, dashboard/src/gql/services/inserRunService.graphql, dashboard/src/gql/services/insertRunService.graphql, dashboard/src/gql/services/insertRunServiceConfig.graphql, dashboard/src/utils/__generated__/graphql.ts
Resolves #2842
___
___
- Refactor Run service creation process
- Use single mutation for service config insertion
- Remove duplicate placeholder creation
- Update GraphQL schema and related types
___
<tr>
<td>
<details>
<summary><strong>ServiceForm.tsx</strong><dd><code>Refactor service creation process in ServiceForm component</code></dd></summary>
<hr>
dashboard/src/features/orgs/projects/services/components/ServiceForm/ServiceForm.tsx
<li>Replace separate insertRunService and insertRunServiceConfig mutations <br>with single insertRunServiceConfig<br> <li> Remove UUID generation for new services<br> <li> Update error handling and …
=> fix (dashboard): duplicate Run placeholders when there is a backend error

.changeset/loud-years-know.md, docs/guides/database/extensions.mdx
Fixes https://github.com/nhost/nhost/issues/3101
___
- Added pg_jsonschema extension to available extensions list
- Included documentation for pg_jsonschema extension usage
- Updated extensions table with pg_jsonschema details
- Minor formatting changes in the document
___
<tr>
<td>
<details>
<summary><strong>loud-years-know.md</strong><dd><code>Add changeset for pg_jsonschema documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.changeset/loud-years-know.md
<li>Added changeset file for @nhost/docs patch<br> <li> Described change as adding docs for …
=> chore (docs): added pg_jsonschema docs

nix/nhost-cli.nix, nix/overlay.nix
Enhancement
___
- Add Nhost CLI package to Nix configuration
- Define Nhost CLI version and platform-specific distributions
- Implement Nix derivation for Nhost CLI installation
- Update overlay to include Nhost CLI package
___
<tr>
<td>
<details>
<summary><strong>nhost-cli.nix</strong><dd><code>Implement Nix package for Nhost CLI</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
nix/nhost-cli.nix
<li>Define Nhost CLI version and platform-specific distributions<br> <li> Implement Nix derivation for Nhost CLI installation<br> …
=> chore: added overlay for nhost cli

.changeset/twelve-llamas-tap.md, dashboard/src/features/orgs/projects/database/dataGrid/components/DataBrowserGridControls/DataBrowserGridControls.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGrid/DataGrid.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridBody/DataGridBody.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridBooleanCell/DataGridBooleanCell.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridCell/DataGridCell.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridConfigProvider/DataGridConfigContext.ts, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridConfigProvider/DataGridConfigProvider.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridConfigProvider/useDataGridConfig.ts, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridDateCell/DataGridDateCell.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridDecimalCell/DataGridDecimalCell.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridFrame/DataGridFrame.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridHeader/DataGridHeader.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridHeaderButton/DataGridHeaderButton.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridHeaderButton/index.ts, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridIntegerCell/DataGridIntegerCell.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridPreviewCell/DataGridPreviewCell.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridTextCell/DataGridTextCell.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/FilesDataGrid/FilesDataGrid.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/FilesDataGridControls/FilesDataGridControls.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/PreviewHeader/PreviewHeader.tsx, dashboard/src/features/orgs/projects/storage/dataGrid/components/PreviewHeader/index.ts, dashboard/src/features/orgs/projects/storage/dataGrid/hooks/usePreviewToggle/index.ts, dashboard/src/features/orgs/projects/storage/dataGrid/hooks/usePreviewToggle/usePreviewToggle.ts
Resolves #2814
___
Enhancement
___
- Add image preview toggle in storage
- Implement preview header with switch control
- Refactor data grid components and imports
- Update file preview functionality
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>21 files</summary><table>
<tr>
<td><strong>DataBrowserGridControls.tsx</strong><dd><code>Update import paths for data grid components</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a href="https://github.com/nhost/nhost/pull/3122/files#diff-640ce3e15c8d5f35d8bbe74792c59493afe5bc69873d2a40f81233da2b02661c">+6/-6</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
<tr> …
=> feat (dashboard): image preview toggle in storage

.changeset/angry-zoos-learn.md, dashboard/src/features/orgs/components/billing/components/SubscriptionPlan/SubscriptionPlan.tsx, dashboard/src/features/orgs/components/common/TransferProjectDialog/TransferProjectDialog.tsx, dashboard/src/features/orgs/projects/ai/settings/components/AISettings.tsx, dashboard/src/features/orgs/projects/common/components/AppLoader/AppLoader.tsx, dashboard/src/features/orgs/projects/custom-domains/settings/components/AuthDomain/AuthDomain.tsx, dashboard/src/features/orgs/projects/custom-domains/settings/components/DatabaseDomain/DatabaseDomain.tsx, dashboard/src/features/orgs/projects/custom-domains/settings/components/HasuraDomain/HasuraDomain.tsx, dashboard/src/features/orgs/projects/custom-domains/settings/components/ServerlessFunctionsDomain/ServerlessFunctionsDomain.tsx, dashboard/src/features/orgs/projects/logs/components/LogsHeader/LogsHeader.tsx, dashboard/src/features/orgs/projects/metrics/settings/components/MetricsSettings/MetricsSettings.tsx, dashboard/src/features/orgs/projects/services/hooks/useRunServices/useRunServices.ts, dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/backups.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/logs.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/settings/authentication.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/settings/custom-domains.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/settings/database.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/settings/index.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/settings/metrics.tsx
Fixes #3127
___
___
- Fix undefined errors in paused projects
- Improve loading states across components
- Handle project and org loading separately
- Update project.id usage for consistency
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><details><summary>1 files</summary><table>
<tr>
<td><strong>SubscriptionPlan.tsx</strong><dd><code>Fix undefined error in org plan handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a href="https://github.com/nhost/nhost/pull/3136/files#diff-2a5f070869055286b669e382b18d656935752803b9a1ef13390ac028c2a48ac4">+3/-3</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
=> fix (dashboard): undefined is not an object issue with paused projects

.changeset/forty-keys-buy.md, docs/guides/functions/runtimes.mdx
___
- Added support for Node.js 22 runtime in functions
- Updated documentation to include Node.js 22 option
- Added changeset for patch version bump
___
<tr>
<td>
<details>
<summary><strong>forty-keys-buy.md</strong><dd><code>Add changeset for Node.js 22 support</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.changeset/forty-keys-buy.md
<li>Added new changeset file for patch version bump<br> <li> Specified '@nhost/docs' package for the change
</details>
</td>
<td><a …
=> chore (docs): added support for nodejs22 to functions

.changeset/brown-suits-drive.md, docs/platform/compute-resources.mdx
___
- Add note about encryption at rest
- Explain encryption for storage, database, and Run services
- Provide warning about volume encryption status
- Include instructions for enabling encryption on older volumes
___
<tr>
<td>
<details>
<summary><strong>brown-suits-drive.md</strong><dd><code>Add changeset for encryption at rest documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.changeset/brown-suits-drive.md
<li>Add changeset file for documentation update<br> <li> Specify patch version bump for '@nhost/docs'
</details>
</td>
<td><a …
=> chore (docs): add note about encryption at rest

.changeset/cyan-suits-provide.md, docs/guides/database/extensions.mdx
Fixes #3131 
___
- Added pgmq extension to Postgres docs
- Updated extensions table with pgmq details
- Included pgmq installation and uninstallation instructions
- Added GitHub resource link for pgmq
___
<tr>
<td>
<details>
<summary><strong>cyan-suits-provide.md</strong><dd><code>Add changeset for pgmq documentation update</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.changeset/cyan-suits-provide.md
<li>Added changeset file for documentation update<br> <li> Specified patch version bump for @nhost/docs
</details>
</td>
<td><a …
=> chore (docs): added pgmq extension to postgres docs

.github/workflows/ci.yaml
Enhancement
___
- Update actions/upload-artifact from v3 to v4
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>ci.yaml</strong><dd><code>Upgrade actions/upload-artifact to latest version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/ci.yaml
- Updated actions/upload-artifact from v3 to v4
</details>
</td>
<td><a href="https://github.com/nhost/nhost/pull/3138/files#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133dd">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
</table></td></tr></tr></tbody></table>
___
> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive …
=> chore: update actions/upload-artifact to v4

.changeset/sixty-turtles-fetch.md, dashboard/docker-entrypoint.sh, dashboard/src/components/layout/AuthenticatedLayout/AuthenticatedLayout.tsx, dashboard/src/components/layout/MainNav/NavTree.tsx, dashboard/src/features/account/settings/components/SocialProvidersSettings/SocialProvidersSettings.tsx, dashboard/src/features/orgs/components/common/TransferOrUpgradeProjectDialog/TransferOrUpgradeProjectDialog.tsx, dashboard/src/features/orgs/layout/OrgLayout/OrgLayout.tsx, dashboard/src/features/orgs/layout/SettingsLayout/SettingsLayout.tsx, dashboard/src/features/orgs/projects/ai/DevAssistant/DevAssistant.tsx, dashboard/src/features/orgs/projects/common/hooks/useIsHealthy/useIsHealthy.ts, dashboard/src/features/orgs/projects/hasura/settings/components/HasuraCorsDomainSettings/HasuraCorsDomainSettings.test.tsx, dashboard/src/features/orgs/utils/local-dashboard/index.ts, dashboard/src/hooks/useSettingsDisabled/index.ts, dashboard/src/hooks/useSettingsDisabled/useSettingsDisabled.ts, dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/ai/assistants/index.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/ai/auto-embeddings/index.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/ai/file-stores/index.tsx, dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/graphql.tsx, dashboard/src/utils/env/env.ts, examples/docker-compose/docker-compose.yaml
___
- Disable settings when no config server variable
- Improve platform-specific page handling
- Enhance error handling and loading states
- Refactor environment variable checks
___
```mermaid
flowchart LR
A["Environment Check"] --> B["Settings Visibility"]
A --> C["Platform-specific Pages"]
D["Error Handling"] --> E["Loading States"]
F["Code Refactoring"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody></tr></tbody></table>
</details>
___
=> fix (dashboard): disable settings when there is no config server env variable present

.changeset/short-jars-report.md, docs/products/database/configuring-postgres.mdx, docs/products/database/extensions.mdx, docs/products/graphql/permissions.mdx
___
- Updated Postgres extensions list and versions
- Added new pg_search extension documentation
- Included custom claims default option
- Minor configuration and formatting improvements
___
```mermaid
flowchart LR
A["Postgres Extensions"] --> B["Update List"]
A --> C["Add pg_search"]
D["Auth Configuration"] --> E["Add Default Claim"]
F["Documentation"] --> G["Improve Formatting"]
```
<tr>
<td>
<details>
<summary><strong>short-jars-report.md</strong><dd><code>Add changeset for version update and feature description</code>&nbsp; </dd></summary>
<hr> …
=> chore (docs): updated postgres extension and added new custom claims default option

.changeset/big-bananas-roll.md, dashboard/e2e/upgrade-project/upgrade-project.test.ts
Bug fix, Tests
___
- Fix upgrade project e2e tests in dashboard
- Add organization type selection in upgrade process
- Update header class in AuthenticatedLayout component
- Include changeset for patch update
___
```mermaid
flowchart LR
A["E2E Test"] -- "Add org type selection" --> B["Upgrade Process"]
C["AuthenticatedLayout"] -- "Update header class" --> D["UI Improvement"]
E["Changeset"] -- "Document patch" --> F["Version Control"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>upgrade-project.test.ts</strong><dd><code>Add organization type selection in upgrade test</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix (dashboard): Fix upgrade project e2e tests

.changeset/clever-dots-complain.md, dashboard/src/pages/signin.tsx, dashboard/src/providers/Auth/AuthContext.ts, dashboard/src/providers/Auth/AuthProvider.tsx
Bug fix
___
- Clear isSigningOut variable on Signin page
- Add clearIsSigningOut function to AuthContext
- Implement clearIsSigningOut in AuthProvider
- Use clearIsSigningOut in signin page useEffect
___
```mermaid
flowchart LR
A["AuthContext"] -- "Add clearIsSigningOut" --> B["AuthProvider"]
B -- "Implement clearIsSigningOut" --> C["Signin Page"]
C -- "Use clearIsSigningOut" --> D["Clear isSigningOut"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Debugging</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>AuthenticatedLayout.tsx</strong><dd><code>Add debug logging in AuthenticatedLayout</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix (dashboard): Clear isSigningOut variable on Signin page

.changeset/cool-toes-impress.md, docs/products/functions/overview.mdx
Documentation
___
- Added response payload limit information
- Clarified execution timeout limits by project tier
- Improved structure of limits section in documentation
___
```mermaid
flowchart LR
A["Functions Limits"] --> B["Execution Timeout"]
A --> C["Response Payload"]
B --> D["Tier-specific timeouts"]
C --> E["6MB hard limit"]
```
<tr>
<td>
<details>
<summary><strong>cool-toes-impress.md</strong><dd><code>Add changeset for functions documentation update</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.changeset/cool-toes-impress.md
<ul><li>Added …
=> fix (docs): functions: added response payload limit

.changeset/mighty-kids-double.md, dashboard/src/features/orgs/layout/OrgLayout/OrganizationGuard.tsx, dashboard/src/features/orgs/layout/OrgLayout/ProjectLayoutContent.tsx, dashboard/src/pages/index.tsx
Bug fix
___
- Check user authentication before redirecting
- Prevent unnecessary redirects for unauthenticated users
- Update logic in OrganizationGuard and ProjectLayoutContent
- Add isUserLoggedIn check in IndexPage component
___
```mermaid
flowchart LR
A["User Authentication"] --> B["isUserLoggedIn"]
B --> C{"Redirect?"}
C -->|Yes| D["Authenticated Redirect"]
C -->|No| E["No Redirect"]
```
<tr>
<td>
<details>
<summary><strong>OrganizationGuard.tsx</strong><dd><code>Add authentication check in OrganizationGuard</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix (dashboard): Check if user is logged in before redirecting

.changeset/quick-kangaroos-perform.md, dashboard/src/features/orgs/components/billing/SubscriptionPlan/SubscriptionPlan.tsx, examples/docker-compose/docker-compose.yaml
___
- Update dashboard image version in docker-compose.yaml
- Improve DialogTitle styling in SubscriptionPlan component
- Add changeset for version bump documentation
___
```mermaid
flowchart LR
A["Docker Compose"] --> B["Dashboard Image"]
B --> C["Version 2.34.0"]
D["SubscriptionPlan Component"] --> E["DialogTitle Styling"]
F["Changeset"] --> G["Version Documentation"]
```
<tr>
<td>
<details>
<summary><strong>docker-compose.yaml</strong><dd><code>Update dashboard image version in docker-compose</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> chore (docker-example): update dashboard image version

.changeset/bright-forks-breathe.md, docs/style.css
Bug fix, Documentation
___
- Update Mintlify dependency to fix documentation issues
- Adjust CSS for better display of hero section
- Ensure proper styling in both light and dark modes
___
```mermaid
flowchart LR
A["Mintlify Update"] --> B["CSS Adjustments"]
B --> C["Hero Section Display"]
B --> D["Light/Dark Mode Styling"]
```
<tr>
<td>
<details>
<summary><strong>style.css</strong><dd><code>Enhance hero section display and mode-specific styling</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/style.css
<ul><li>Added <code>display: inline-block;</code> to hero section h1<br> <li> Adjusted styling …
=> fix (docs): fixes to changes in mintlify breaking our docs

.changeset/few-fans-collect.md, dashboard/e2e/fixtures/auth-hook.ts, dashboard/e2e/setup/auth.setup.ts, dashboard/e2e/utils.ts, dashboard/package.json, dashboard/src/components/layout/MainNav/NavTree.tsx, dashboard/src/features/orgs/components/billing/FinishUpgradeOrganizationProcess/FinishUpgradeOrganizationProcess.tsx, pnpm-lock.yaml
___
- Update navbar after organization and project operations
- Remove unnecessary useMemo and refetch calls
- Improve UI responsiveness in upgrade process
- Add changeset for patch version bump
___
```mermaid
flowchart LR
A["NavTree Component"] -- "Remove useMemo" --> B["Improved Performance"]
C["FinishUpgradeOrganizationProcess"] -- "Remove refetchOrgs" --> D["Optimized Upgrade Flow"]
E["Changeset"] -- "Add patch version" --> F["Version Control"]
```
<tr>
<td>
<details>
<summary><strong>NavTree.tsx</strong><dd><code>Optimize NavTree rendering by removing useMemo</code>&nbsp; …
=> fix (dashboard): Update navbar after org and project operations

.changeset/little-coats-call.md, dashboard/src/features/orgs/projects/database/dataGrid/hooks/useCreateTableMutation/prepareCreateTableQuery.ts
Bug fix
___
- Allow creating database tables without primary key
- Update logic to handle empty primary key values
___
```mermaid
flowchart LR
A["Table Creation"] --> B["Primary Key Check"]
B -- "Empty" --> C["Skip Primary Key"]
B -- "Not Empty" --> D["Add Primary Key"]
```
<tr>
<td>
<details>
<summary><strong>prepareCreateTableQuery.ts</strong><dd><code>Update primary key check in table creation query</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/features/orgs/projects/database/dataGrid/hooks/useCreateTableMutation/prepareCreateTableQuery.ts …
=> fix (dashboard): Allow creating tables without primary key

dashboard/src/features/auth/AuthProviders/Github/hooks/useGithubAuthentication/useGithubAuthentication.ts, dashboard/src/features/auth/SignUp/SignUpTabs/SignUpWithEmailAndPassword/hooks/useOnSignUpWithPasswordHandler.ts, dashboard/src/features/auth/SignUp/SignUpTabs/SignUpWithSecurityKey/hooks/useSignupWithSecurityKeyHandler.ts, dashboard/src/features/auth/SignUp/SignUpWithGithub/SignUpWithGithub.tsx, dashboard/src/lib/segment.ts, dashboard/src/pages/signup.tsx
Enhancement, Bug fix
___
- Disable Segment analytics across the dashboard
- Remove anonId from authentication processes
- Adjust Google Ads initialization with logging
___
```mermaid
flowchart LR
A["Segment Analytics"] -- "Disabled" --> B["Dashboard"]
C["Authentication"] -- "Remove anonId" --> D["Auth Flows"]
E["Google Ads"] -- "Add logging" --> F["Initialization"]
```
<tr>
<td>
<details>
<summary><strong>useGithubAuthentication.ts</strong><dd><code>Remove Segment anonId from GitHub authentication</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> fix (dashboard): Disable segment

.changeset/rich-dragons-attend.md, dashboard/src/components/form/ControlledAutocomplete/ControlledAutocomplete.tsx, dashboard/src/components/ui/v2/Autocomplete/Autocomplete.tsx, dashboard/src/features/orgs/projects/database/dataGrid/components/BaseColumnForm/BaseColumnForm.tsx, dashboard/src/features/orgs/projects/database/dataGrid/components/BaseTableForm/ColumnEditorRow/ColumnEditorRow.tsx, dashboard/src/features/orgs/projects/database/dataGrid/components/DataBrowserGrid/DataBrowserGrid.tsx, dashboard/src/features/orgs/projects/database/dataGrid/components/DatabaseRecordInputGroup/DatabaseRecordInputGroup.tsx, dashboard/src/features/orgs/projects/database/dataGrid/hooks/useCreateColumnMutation/prepareCreateColumnQuery.ts, dashboard/src/features/orgs/projects/database/dataGrid/hooks/useCreateTableMutation/prepareCreateTableQuery.test.ts, dashboard/src/features/orgs/projects/database/dataGrid/hooks/useCreateTableMutation/prepareCreateTableQuery.ts, dashboard/src/features/orgs/projects/database/dataGrid/hooks/useTableQuery/fetchTable.ts, dashboard/src/features/orgs/projects/database/dataGrid/hooks/useUpdateColumnMutation/prepareUpdateColumnQuery.test.ts, dashboard/src/features/orgs/projects/database/dataGrid/hooks/useUpdateColumnMutation/prepareUpdateColumnQuery.ts, dashboard/src/features/orgs/projects/database/dataGrid/hooks/useUpdateTableMutation/prepareUpdateTableQuery.test.ts, dashboard/src/features/orgs/projects/database/dataGrid/types/dataBrowser/dataBrowser.ts, dashboard/src/features/orgs/projects/database/dataGrid/utils/inputHelpers/getInputType/getInputType.test.ts, dashboard/src/features/orgs/projects/database/dataGrid/utils/normalizeColumnType/index.ts, dashboard/src/features/orgs/projects/database/dataGrid/utils/normalizeColumnType/normalizeColumnType.ts, dashboard/src/features/orgs/projects/database/dataGrid/utils/normalizeDatabaseColumn/normalizeDatabaseColumn.test.ts, dashboard/src/features/orgs/projects/database/dataGrid/utils/normalizeDatabaseColumn/normalizeDatabaseColumn.ts, dashboard/src/features/orgs/projects/database/dataGrid/utils/postgresqlConstants/postgresqlConstants.ts, dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridTextCell/DataGridTextCell.tsx
Enhancement
___
- Add custom column types to database tables
- Improve handling of user-defined data types
- Update UI components for custom type support
- Refactor column type normalization and validation
___
```mermaid
flowchart LR
A["Column Type Handling"] -- "Extend" --> B["Custom Types"]
B -- "Update" --> C["UI Components"]
B -- "Refactor" --> D["Type Normalization"]
D -- "Improve" --> E["Data Validation"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>15 files</summary><table>
<tr>
<td><strong>Autocomplete.tsx</strong><dd><code>Enhance Autocomplete component for custom types</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> feat (dashboard): add custom types to column types

.changeset/new-eels-run.md, dashboard/src/features/orgs/projects/database/dataGrid/components/ColumnAutocomplete/ColumnAutocomplete.test.tsx, dashboard/src/features/orgs/projects/database/dataGrid/components/ColumnAutocomplete/ColumnAutocomplete.tsx, dashboard/src/features/orgs/projects/database/dataGrid/hooks/useTableQuery/useTableQuery.ts, dashboard/src/tests/msw/mocks/rest/hasuraMetadataQuery.ts, dashboard/src/tests/msw/mocks/rest/tableQuery.ts, dashboard/src/tests/testUtils.tsx
Bug fix, Tests, Enhancement
___
- Add MSW mock for nested relationship metadata
- Add test verifying nested relationships display
- Simplify `CommandList` rendering logic
- Introduce `fireClickEvent` helper in tests
___
```mermaid
flowchart LR
metadata["\"MSW nested metadata mock\""]
component["\"ColumnAutocomplete component\""]
ui["\"Displays nested relationship options\""]
metadata -- "provides nested data" --> component
component -- "renders options" --> ui
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><details><summary>4 files</summary><table>
<tr>
<td><strong>ColumnAutocomplete.test.tsx</strong><dd><code>Add nested relationship test and router …
=> fix (dashboard): Show nested relationships in row permissions

docs/reference/javascript/nhost-js/graphql.mdx, packages/nhost-js/src/graphql/__tests__/docstrings.test.ts, packages/nhost-js/src/graphql/index.ts
Tests, Documentation
___
- Add GraphQL request test with variables support
- Update qql test to include variables option
- Extend SDK docstrings with variables usage section
- Enhance documentation with variables example
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>docstrings.test.ts</strong><dd><code>Enhance tests with variables usage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/nhost-js/src/graphql/__tests__/docstrings.test.ts
<ul><li>Added new "request with …
=> chore (docs): udpate graphql documentation to include example with variables

README.md, packages/nhost-js/README.md
Documentation
___
- Update root README code examples
- Switch to `createClient` API and adjust auth methods
- Change GraphQL request syntax to object form
- Simplify install commands in package README
___
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Revise root README examples and links</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
<ul><li>Changed code block language to TypeScript<br> <li> Replaced <code>NhostClient</code> with …
=> chore(docs): update README

.github/workflows/cli_checks.yaml, .github/workflows/cli_test_new_project.yaml, cli/Makefile, cli/get.sh, cli/project.nix, flake.nix
Tests, Enhancement
___
- Add `test_cli_build` job in CLI CI workflow
- Create `cli_test_new_project` reusable workflow
- Define AWS, Nix, and artifact steps
___
```mermaid
flowchart LR
A[".github/workflows/cli_checks.yaml"] -- "adds job" --> B["test_cli_build"]
B -- "uses workflow" --> C[".github/workflows/cli_test_new_project.yaml"]
```
<tr>
<td>
<details>
<summary><strong>cli_checks.yaml</strong><dd><code>Add `test_cli_build` CI job</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> chore(ci): test cli can create and start new project

.github/dependabot.yaml, .github/workflows/ci_release.yaml, .github/workflows/cli_release.yaml, .github/workflows/dashboard_release.yaml, .github/workflows/storage_release.yaml, .github/workflows/wf_docker_push_image.yaml, .github/workflows/wf_docker_push_image_ecr.yaml
Enhancement
___
- Add storage release pipeline job
- Remove `NAME` inputs for CLI and dashboard workflows
- Introduce `storage_release.yaml` workflow
- Enable custom `CONTAINER_REGISTRY` in docker push action
___
```mermaid
flowchart LR
EXTRACT["extract-project"]
CLI["cli: release"]
DASH["dashboard: release"]
JS["js: release"]
STORAGE["storage: release"]
BUILD["build artifacts"]
HUB["push to Docker Hub"]
ECR["push to ECR"]
EXTRACT --> CLI
EXTRACT --> DASH
EXTRACT --> JS
EXTRACT --> STORAGE
STORAGE --> BUILD
BUILD --> HUB
BUILD --> ECR
```
<tr>
<td>
<details> …
=> chore(ci): implement storage releases

.github/workflows/gen_ai_review.yaml
Enhancement
___
- Use `${{ vars.GEN_AI_MODEL }}` for `config.model`
- Use `${{ vars.GEN_AI_MODEL_TURBO }}` for `config.model_turbo`
- Remove hardcoded Anthropic model names
___
<tr>
<td>
<details>
<summary><strong>gen_ai_review.yaml</strong><dd><code>Use variables for AI model configs</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/gen_ai_review.yaml
<ul><li>Replaced hardcoded <code>config.model</code> with <code>${{ vars.GEN_AI_MODEL …
=> chore(ci): use variables in gen_ai_review workflow to configure models

dashboard/package.json, dashboard/src/features/orgs/layout/OrgLayout/ProjectLayoutContent.tsx, dashboard/src/features/orgs/projects/authentication/users/components/CreateUserForm/CreateUserForm.tsx
___
Bug fix
___
- Delay loading state if project data empty
- Delay auth URL generation until submit
- Add error handling for missing project data
- Remove eager URL setup in form
___
<tr>
<td>
<details>
<summary><strong>ProjectLayoutContent.tsx</strong><dd><code>Add empty project loading check</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/features/orgs/layout/OrgLayout/ProjectLayoutContent.tsx
<ul><li>Imported …
=> fix (dashboard): delay generating auth service url when creating users

.github/actions/validate-pr-title/action.yaml, .github/workflows/wf_build_artifacts.yaml, .github/workflows/wf_check.yaml
Enhancement
___
- Add composite GitHub Action to validate PR titles
- Define valid TYPE and PKG patterns for titles
- Integrate title validation step in CI workflow
- Provide user-friendly error messages on failure
___
```mermaid
flowchart LR
W["Workflow wf_check.yaml"] -- "uses validate-pr-title action" --> A["Action validate-pr-title/action.yaml"]
```
<tr>
<td>
<details>
<summary><strong>action.yaml</strong><dd><code>Add composite PR title validation action</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> chore(ci): validate PR title
