nhost/nhost

- examples/nhost-react-query/pages/login.tsx
- examples/nhost-react-query/src/modules/auth/register/RegisterForm.tsx
Fixed two minor issues in the Nhost with React-Query example example:
- The register form was not passing the `email` and `password` to the `auth.register` function correctly.
- The login form is never shown due to the `user === null` check
> Fix login and register for Nhost with React-Query example

- docs/content/docs/reference/supporting-libraries/react-auth.mdx
This PR adds the missing shell language identifier for the [react-auth](https://docs.nhost.io/reference/supporting-libraries/react-auth) page.
> Adds missing lang identifier for code block

- .changeset/eleven-forks-relate.md
- package.json
- packages/react-auth/package.json
- packages/react-auth/src/index.tsx
- pnpm-lock.yaml
Close #187 
Another minor point: `pnpm run clean:all` now also removes the `.nhost` folders
> Fix useNhostAuth typings

- .changeset/long-cars-melt.md
- docs/content/docs/reference/sdk/storage.mdx
- packages/hasura-storage-js/src/hasura-storage-client.ts
It aims to make a clear distinction between `storage.getPublicUrl` and `storage.getPresginedUrl`
`storage.getUrl` is now deprecated.
fix #178
> refactor(hasura-storage-js): rename `storage.getUrl` to `storage.getPublicUrl`

- .changeset/eight-scissors-turn.md
- .config/esbuild.lib.js
- packages/hasura-auth-js/package.json
- packages/hasura-storage-js/package.json
- packages/nhost-js/package.json
Some systems based on older versions of Webpack or Babel don't support the current esbuild configuration e.g, [this issue](https://github.com/nhost/nhost/issues/275).
> fix: change target ES module build target to es2019

- .changeset/famous-laws-sit.md
- packages/hasura-storage-js/src/hasura-storage-api.ts
- packages/hasura-storage-js/src/hasura-storage-client.ts
This PR aims to make `x-hasura-admin-secret` request header configuration available when using storage related functions (upload, delete, etc.). This would allow users of the SDK leverage our functions where file management should be restricted to administrators only.
Comments were also added to `setAccessToken` and `setAdminSecret` functions. The way these setters work has also been slightly changed.
Initial approach:
```js
// ... rest of the code ...
nhost.storage.setAdminSecret('my-admin-secret');
const { fileMetadata, error } = await nhost.storage.upload({
/* ... */
});
```
Final approach:
```js
// ... rest of the code ...
const { fileMetadata, error } = await nhost.storage
.setAdminSecret('my-admin-secret')
.upload({
/* ... */
});
```
**Note: It's worth mentioning that it's not …
> feat: admin secret for storage

- packages/core/src/machines/index.ts
In the next cycle, hasura-auth will only send the refresh token in the hash, and will add the
redirection type as a query parameter. We will then be able to remove/hide the hash from the url as
soon as the refresh token has been used
> fix: keep location.hash in email redirections

- .changeset/red-tables-punch.md
- docs/content/docs/reference/react/hooks.mdx
- docs/content/docs/reference/react/protecting-routes.mdx
- examples/nextjs/components/Header.tsx
- examples/nextjs/components/protected-route.tsx
- examples/nextjs/pages/client-side-auth-guard.tsx
- examples/nextjs/pages/third.tsx
- examples/react-apollo/src/components/auth-gates.tsx
- packages/react/src/hooks/common.ts
- packages/react/src/hooks/deprecated.ts
- packages/react/src/hooks/registration.ts
When using both `useAuthLoading` and `useAuthenticated` together, the hooks rerender independently from each other.
As a result, when a user loads the page while he previously authenticated, the hooks values were chronologically:
| isLoading | isAuthenticated |
| --------- | --------------- |
| `true`    | `false`         |
| `false`   | `false`         |
| `false`   | `true`          |
The intermediate (`false`, `false`) is incorrect and is causing issues when using an authentication gate.
It is therefore recommended to stop using `useAuthLoading`, and to use `useAuthenticationStatus` instead, in order to keep the loading state and the authentication in sync within the same hook.
Usage:
```js
const { isLoading, isAuthenticated } = useAuthenticationStatus()
```
Fixes [this …
> Deprecate `useAuthLoading` and introduce `useAuthenticationStatus`

- docs/components/MDX/CodeComponent.tsx
The `SyntaxHighlighter` component was not capturing the language, and Typescript was not enabled.
That being said, it can be further improved in adjusting [lightTheme.js](https://github.com/nhost/nhost/blob/main/docs/data/lightTheme.js) so `ts` - would anyone know how to do?
> docs: pass language to react-syntax-highlighter

- docs/content/docs/reference/react/hooks.mdx
Fix a typo in the `nhsot/react` documentation in the code example. 
The imported hook had a wrong name
> Fix a type in react documentation

- .changeset/old-poets-design.md
- packages/core/src/client.ts
- packages/hasura-auth-js/src/hasura-auth-client.ts
- packages/nhost-js/src/core/nhost-client.ts
The authentication events where not set correctly, leading the main Nhost client not to update internal states of storage/graphql/functions sub-clients when using non-react clients.
The use of private fields (`#`) is also avoided as they conflict with the use of proxies in Vue, leading to errors in the upcoming Vue library.
Fixes #373 and #378
> Keep authentication status and access token in sync

- .changeset/thirty-scissors-pull.md
- packages/nextjs/package.json
- packages/nextjs/src/get-session.ts
- pnpm-lock.yaml
This PR fixes #371 and also adds the missing TSDoc to the exposed `getNhostSession` function.
> fix: getNhostSession typing improvements, missing TSDoc

- docs/docusaurus.config.js
Updated edit link to link to edit page instead of blob page.
> Docs: edit link instead of blob

- docs/README.md
Mac put this weird whitespace-like character here, therefore the README was rendered incorrectly.
> Update Docs README.md

- .changeset/tricky-drinks-laugh.md
- packages/core/src/machines/index.ts
When signin up, an invalid password was returning the `invalid-email` error, and an invalid email was returning `invalid-password`.
> fix: invalid password and email errors on sign up

- .changeset/bright-apples-sparkle.md
- .changeset/quick-swans-care.md
- examples/nextjs/nhost/config.yaml
- examples/react-apollo/nhost/config.yaml
- packages/core/src/machines/index.ts
- packages/core/src/machines/index.typegen.ts
- packages/nextjs/src/create-server-side-client.ts
- Get the refresh token in the right place in the url
Hasura-auth puts the refresh token in the url as `refreshToken`, but it is not stored using the same key in localStorage / the cookie. This fix makes the right correspondance between the two.
- Clean `refreshToken` and `type` from the url when the user is already signed in
- Bump hasura-auth versions in the examples
> fix: get the refresh token in the right place in the url

- examples/docker-compose/docker-compose.yaml
I ran into an issue where I couldn't sign up users because the auth service wasn't able to connect to mailhog.
That caused the auth service to not send an email and not respond to the HTTP request.
fixes #499 
I'm wondering if anyone else had this issue. If I'm the only one then maybe this PR is obsolete.
> Adds environment variables to auth service

- examples/nextjs/next.config.js
- examples/nextjs/package.json
- pnpm-lock.yaml
It is not required in the new monorepo setup
> refactor: stop using next-transpile-modules

- packages/react/package.json
- pnpm-lock.yaml
`@xstate/react` was downgraded to `2.0.1` by mistake which does not support `react@18.x`. This change fixes #537.
> fix: @xstate/react bump to support React 18

- .changeset/moody-ghosts-clap.md
- packages/core/package.json
- packages/hasura-auth-js/package.json
- packages/hasura-storage-js/package.json
- packages/hasura-storage-js/src/hasura-storage-api.ts
- packages/nhost-js/package.json
- pnpm-lock.yaml
https://discord.com/channels/552499021260914688/973630292910833754/973630524025344051
Axios' latest release [reverted a change](https://github.com/axios/axios/pull/3785/files) that intentionally caused `Content-Type` to be removed from network requests.
The version bump is not enough solve the issue for React Native applications, because the `Content-Type` automatically determined by the environment was `application/x-www-form-urlencoded` instead of `multipart/form-data`, so we are manually overriding the value for file upload requests.
> Bump `axios` and set correct `Content-Type` for file upload

- .changeset/hip-ants-fly.md
- packages/core/src/utils.ts
- packages/core/tests/utils.test.ts
URLs where malformed When the client URL was defining query parameters and a relative `redirectTo` URL was passed on as an option.
It is now possible to define query parameters in both the base client URL and the relative `redirectTo`
> accept query parameters from both relative `redirectTo` URLs and the client URL

- .changeset/cool-shrimps-reply.md
- config/vite.lib.config.js
- docs/docs/platform/quickstarts/vue.mdx
- docs/docs/reference/vue/apollo.mdx
- examples/vue-apollo/src/pages/ApolloPage.vue
- examples/vue-quickstart/src/pages/profile.vue
- packages/apollo/src/index.ts
This fixes a bug where it's required to have react in a vue project.
@apollo/client exports code related to react.
@apollo/client/core does not not.
Ref: https://github.com/apollographql/apollo-client/blob/main/src/index.ts
Edit:
I'm not sure what I saw. There must have been a `feat/vue` branch here very recently. Let me know if I should re-branch this to `bug/apollo-imports` or so
> 🐛 imports from @apollo/client/core for vue

- docs/docs/platform/serverless-functions.mdx
The switch for yarn should `D`, not `d`.
> Corrected the yarn switch for installing express

- .changeset/fair-brooms-sniff.md
- config/vite.lib.config.js
- config/vite.lib.umd.config.js
- config/vite.react.umd.config.js
- config/vite.vue.umd.config.js
- docs/docs/reference/docgen/javascript/nhost-js/content/nhost-graphql-client/content/01-request.mdx
- docs/docs/reference/docgen/javascript/nhost-js/content/nhost-graphql-client/content/02-get-url.mdx
- docs/docs/reference/docgen/javascript/nhost-js/content/nhost-graphql-client/content/03-set-access-token.mdx
- docs/docs/reference/docgen/javascript/nhost-js/content/nhost-graphql-client/index.mdx
- docs/docs/reference/docgen/javascript/nhost-js/types/nhost-graphql-constructor-params.mdx
- packages/apollo/package.json
- packages/core/package.json
- packages/hasura-auth-js/package.json
- packages/hasura-storage-js/package.json
- packages/nextjs/package.json
- packages/nhost-js/package.json
- packages/nhost-js/src/clients/graphql.ts
- packages/react-apollo/package.json
- packages/react-auth/package.json
- packages/react/package.json
- packages/vue/package.json
- pnpm-lock.yaml
```
SyntaxError: Named export 'NhostClient' not found. The requested module '@nhost/nhost-js' is a CommonJS module, which may not support all module.exports as named exports.
(node:56887) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
```
Updated `exports` field of all packages to move away from `.es.js` files to `.mjs` when using `import` statements on the consumer side. Also fixed an issue related to this where `graphql` package was incorrectly imported in `@nhost/nhost-js`.
> fix: Package bundling / Node.js environment

- .changeset/tricky-peaches-pump.md
- examples/nextjs/components/OauthLinks.tsx
- packages/core/src/utils.ts
- packages/core/tests/utils.test.ts
- packages/react/src/useProviderLink.ts
- pnpm-lock.yaml
The client URL is set to `window.location.origin`, so it can rewrite redirection urls that are
passed on to authenticaion methods. However, `clientUrl` is set to `''` when running on the server
side. This fix then avoid raising an error when trying to rewrite `redirectTo` on non-browser
environment, and forces `useProviderLink` to be rendered on the client side.
> fix: correct rewriting options when `clientUrl` is not available

- .changeset/violet-poets-melt.md
- packages/vue/src/helpers.ts
- packages/vue/tests/main.test.ts
The `nestedUnref` helper was not correctly un-refing nested values. For instance, the values the properties of the following metadata were still `refs`:
```jsx
const { signUpEmailPassword } = useSignUpEmailPassword()
const firstName = ref('John')
const lastName = ref('Doe')
signUpEmailPassword(
email: 'john@world.com',
password: 'not-1234',
{
metadata: { firstName, lastName }
}
);
```
> Correct use of ref values in action options

- examples/react-apollo/.vscode/settings.json
- examples/react-apollo/cypress/e2e/4-authenticated/apollo.cy.ts
- examples/react-apollo/graphql.config.yaml
- examples/react-apollo/nhost/metadata/databases/default/tables/public_todos.yaml
- examples/react-apollo/nhost/metadata/databases/default/tables/tables.yaml
- examples/react-apollo/nhost/migrations/default/1654842138617_create_table_public_todos/down.sql
- examples/react-apollo/nhost/migrations/default/1654842138617_create_table_public_todos/up.sql
- examples/react-apollo/nhost/migrations/default/1654843938796_drop_table_public_books/down.sql
- examples/react-apollo/nhost/migrations/default/1654843938796_drop_table_public_books/up.sql
- examples/react-apollo/package.json
- examples/react-apollo/src/apollo/index.tsx
- examples/react-apollo/src/generated.ts
- pnpm-lock.yaml
- replace the `books` table by a `todos` table
- adjust the Apollo page to add a todo item to the list
- filter user permissions to only see and modify their own todo items
- use Apollo codegen to generate typings for the default user role, and to enable autocompletion with VS code
- Add a Cypress test for the todo list
> docs: replace the `books` table by a `todos` table

- docs/docs/platform/graphql/permissions.md
Mention how Nhost prefixes the custom JWT claims locally and correct example path.
> Correct permission variables section

- examples/react-apollo/src/components/AuthLink.tsx
- examples/react-apollo/src/components/OauthLinks.tsx
- examples/react-apollo/src/sign-in/index.tsx
- examples/react-apollo/src/sign-up/index.tsx
Authentication links were rendered as a react-router `Link` instead of a simple `a` tag. As the `Link` tag does not support external url, it ended up with incorrect urls such as 
```
https://frontend.com/sign-in/https://backend.nhost.run/v1/auth/signin/provider/github
```
> React-apollo example: correct links to external urls (social providers)

- .changeset/afraid-carpets-cough.md
- packages/apollo/package.json
- packages/core/package.json
- packages/hasura-auth-js/package.json
- packages/hasura-storage-js/package.json
- packages/nextjs/package.json
- packages/nhost-js/package.json
- packages/react-apollo/package.json
- packages/react-auth/package.json
- packages/react/package.json
- packages/vue/package.json
This PR fixes #730 that is caused by a regression introduced in [`@nhost/nhost-js@1.1.10`](https://github.com/nhost/nhost/releases/tag/%40nhost%2Fnhost-js%401.1.10).
> fix: `exports` field to support server-side environments

- docs/docs/platform/authentication/sign-in-methods/index.md
When I was searching for the "redirectTo" param I didn't find anything in the docs, maybe it was my fault but I've missed this.
Sorry if this is duplicated.
> docs: Add "redirectTo" to provider sign-in

- .changeset/lovely-windows-accept.md
- packages/core/src/storage.ts
- packages/nextjs/package.json
- packages/nextjs/src/create-server-side-client.ts
- pnpm-lock.yaml
- Using same cookie package ([`js-cookie`](https://www.npmjs.com/package/js-cookie)) for both `@nhost/nextjs` and `@nhost/core` packages.
- Adding `expires` to avoid the cookie turning into a session cookie that some browsers aggressively destroy.
> patch: Using same cookie package and made sure cookies are not becoming session cookies

- packages/core/src/types.ts
Discord wasn't present in the provider type, making it throw a typescript error
> Add discord to provider types

- .changeset/nine-students-design.md
- packages/apollo/package.json
- packages/core/package.json
- packages/hasura-auth-js/package.json
- packages/hasura-storage-js/package.json
- packages/nextjs/package.json
- packages/nhost-js/package.json
- packages/react-apollo/package.json
- packages/react-auth/package.json
- packages/react/package.json
- packages/vue/package.json
After installing @nhost/react and @nhost/react-apollo into a React Native 0.69.1 project, attempting to start the Metro bundler fails:
```
$ npm run start                                                                                                                                                                      
> phenomenological@0.0.1 start                                                                        
> react-native start                                                                                                                                                                                        
error Failed to load configuration of your project. …
```
> Fix React Native build

- examples/codegen-react-apollo/nhost/config.yaml
- examples/codegen-react-query/nhost/config.yaml
- examples/multi-tenant-one-to-many/nhost/config.yaml
- examples/nextjs/nhost/config.yaml
- examples/react-apollo-crm/nhost/config.yaml
- examples/react-apollo/nhost/config.yaml
- examples/vue-apollo/nhost/config.yaml
- nhost-cloud.yaml
- packages/hasura-auth-js/nhost/config.yaml
- packages/nhost-js/nhost/config.yaml
Changes made in modifying [nhost-cloud.yaml](https://github.com/nhost/nhost/pull/884/files#diff-8d75136358596200fe1b1f76630959618cf170fb4c8d003fd03d34cfeae09bdb). It runs tests against bumped versions of hasura, hasura-auth and hasura-storage.
Do not merge until service versions are effectively changed in the cloud, as examples from this repo are deployed into the cloud with production versions.
> Bump hasura version to 2.10.1

- .changeset/strange-glasses-whisper.md
- packages/core/src/hasura-auth.ts
The error code was not captured correctly when the requested url was incorrect, as the `response?.data` property in `AxiosError` could be null, ending in an error when getting `response?.data.error`
> fix: 🐛 Return a `network` error code

- .changeset/eleven-turkeys-clean.md
- .changeset/unlucky-months-work.md
- packages/nextjs/src/create-server-side-client.ts
The nextjs package creates its own NhostClient with a custom `clientStorage` that reads cookies to check if there's an active user session. However, it doesn't read cookies from the nextjs context, meaning that it'll never find the `nhostRefreshToken` cookie when used inside `getServerSideProps`. 
Fixes #886 and #930.
> fix: read nextjs context cookie in clientStorage

- examples/vue-quickstart/src/main.ts
This file has diverged from the respective doc [page](https://docs.nhost.io/platform/quickstarts/vue#configure-nhost-with-vue). 
Maybe the docs should be updated instead to match the current file, in any case, i think will be nice to fix this and avoid confusion & friction to new comers trying the vue integration out.
> Recover documentation consistency

- examples/react-apollo/cypress/e2e/3-sign-in/token.cy.ts
- examples/react-apollo/src/components/auth-gates.tsx
- packages/react/src/useAuthenticationStatus.ts
- packages/vue/src/useAuthenticationStatus.ts
- `useAuthenticationStatus` was not re-rendered when `connectionAttempts` was changing
- the e2e test on offline auto-signin needed to be adapted
> fix: refresh useAuthenticationStatus on conn attempt changes

- package.json
Our monorepo is not compatible with Node 18.
This PR raises a warning when Node version is higher than 16.
Moreover the `packageManager` has been adjusted to use the right `pnpm`
> chore: 🤖 warn about node 14 or 16, & adapt packageManager

- .github/workflows/tests.yaml
Stop using `::set-output` in GitHub actions as [they are now deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
> ci: remove deprecated set-output

- .github/actions/install-dependencies/action.yaml
- .github/workflows/changesets.yaml
- .github/workflows/tests.yaml
- fix GH action with the correct [set output syntax](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
- bump `pnpm/action-setup` GH action to suppress `set-state` warnings
- bump `actions/checkout` to suppress node 12 warnings
> fix: correct e2e matrix and bump GH actions

- examples/serverless-functions/package.json
Don't try to publish the package - see [this action](https://github.com/nhost/nhost/actions/runs/3427734944/jobs/5711100627)
> fix: make "@nhost-examples/serverless-functions private

- .github/actions/install-dependencies/action.yaml
- .github/workflows/tests.yaml
The `tests` GH action will filter out e2e tests that are not depending on the changes of the PR
> ci: 🎡 Skip e2e jobs when not affected by the changes in the PR

- .github/workflows/changesets.yaml
- dashboard/Dockerfile
Before merging this PR, we should remove the existing dashboard tag:
```sh
git tag -d @nhost/dashboard@0.2.0
git push --delete origin @nhost/dashboard@0.2.0
```
> ci: use turborepo cache when building images

- .github/workflows/changesets.yaml
@szilarddoro we missed a typo
same thing:
```
git tag -d @nhost/dashboard@0.2.0
git push --delete origin @nhost/dashboard@0.2.0
```
> ci: fix typo

- .github/workflows/changesets.yaml
- dashboard/Dockerfile
- turbo.json
problems:
1. we were sending the entire tag `@nhost/dashboard@0.2.0` instead of `0.2.0`
As a result, the semver version used by docker meta was `v@nhost/dashboard@0.2.0` instead of `v0.2.0`
2. turborepo did not restore the cache correctly
We'll need to remove the tag again
> ci: fix version

- .changeset/mean-cats-explain.md
- packages/core/src/storage.ts
[Firefox raises a warning when no same-site value is set](https://discord.com/channels/552499021260914688/1044122100228706334/1044242141888651265)
> fix: 🐛 Set same-site cookie to `lax`

- .github/actions/install-dependencies/action.yaml
- package.json
In particular `strict-peer-dependencies` should default to `false` - see [v7.13.5 release notes](https://github.com/pnpm/pnpm/releases/tag/v7.13.5)
> chore: bump pnpm version to v7.17.0

- dashboard/graphql.config.yaml
We don't have access to the functions folder in this repository, and it breaks the GraphQL codegen process.
> fix(dashboard): remove functions folder reference from codegen config

- package.json
The pre-commit hook will fail with Node versions less than 16 which prevents contributions.
> Update minimum version of node

- DEVELOPERS.md
Lessons learned from our discussion with Sheena and Chris:
- Don't use Node 14
- Run `pnpm run build` at least once before any commit, as `docgen` needs to be built
> docs: update developer's guide

- .github/workflows/changesets.yaml
This PR adds the ability to trigger production deployments when a new tag is created for the Dashboard.
> feat(dashboard): add Vercel deployment

- .changeset/nice-feet-work.md
- dashboard/Dockerfile
- dashboard/README.md
- dashboard/docker-entrypoint.sh
- dashboard/src/components/applications/HasuraData.tsx
- dashboard/src/hooks/dataBrowser/useCreateColumnMutation/createColumnMigration.ts
- dashboard/src/hooks/dataBrowser/useCreateTableMutation/createTableMigration.ts
- dashboard/src/hooks/dataBrowser/useDeleteColumnMutation/deleteColumnMigration.ts
- dashboard/src/hooks/dataBrowser/useDeleteTableMutation/deleteTableMigration.ts
- dashboard/src/hooks/dataBrowser/useTrackForeignKeyRelationsMutation/trackForeignKeyRelationsMigration.ts
- dashboard/src/hooks/dataBrowser/useTrackTableMutation/trackTableMigration.ts
- dashboard/src/hooks/dataBrowser/useUpdateColumnMutation/updateColumnMigration.ts
- dashboard/src/hooks/dataBrowser/useUpdateTableMutation/updateTableMigration.ts
- dashboard/src/hooks/useAppClient.ts
- dashboard/src/utils/env.ts
- dashboard/src/utils/helpers.ts
- dashboard/src/utils/nhost.ts
- packages/nhost-js/src/utils/helpers.ts
- packages/nhost-js/tests/utils.test.ts
I created an environment variable (`NEXT_PUBLIC_NHOST_LOCAL_BACKEND_PORT`) to let the CLI pass a custom port when a user wants to change it.
I've made some changes to other environment variables to make them more consistent:
`NEXT_PUBLIC_NHOST_MIGRATIONS_URL` -> `NEXT_PUBLIC_NHOST_MIGRATIONS_PORT`
`NEXT_PUBLIC_NHOST_HASURA_URL` -> `NEXT_PUBLIC_NHOST_HASURA_PORT`
`...NHOST_MIGRATIONS_PORT` and `...NHOST_HASURA_PORT` only make sense in a local environment. I think we want to use `...NHOST_LOCAL...` here too.
> feat(dashboard): make backend port configurable

- .github/workflows/changesets.yaml
- .github/workflows/dashboard.yaml
- .github/workflows/packages.yaml
As the Turbo team is `nhost`, GH redacts anything in the actions that contains `nhost`. In particular, [it prevents the `e2e` matrix to run](https://github.com/nhost/nhost/actions/runs/3566725407/jobs/5993533225#step:18:2)
> ci: hardcode turbo team

- .github/workflows/ci.yaml
- .github/workflows/dashboard.yaml
- rename the `Packages` workflow to `Continuous Integration`
- deactivate the `Dashboard` workflow on pull request as the dashboard build/test/lint jobs now run in the CI workflow
> ci: adjust workflows

- examples/vue-quickstart/.eslintrc.js
- examples/vue-quickstart/package.json
Changesets is not able to bump the example's version as the version field is missing in its `package.json` field.
See https://github.com/nhost/nhost/pull/1274
> chore: add missing version field to the vue-starter example

- .changeset/two-owls-promise.md
- dashboard/src/components/settings/environmentVariables/EnvironmentVariableSettings/EnvironmentVariableSettings.tsx
> fix(dashboard): correct section paddings when no env vars

- .changeset/fair-students-enjoy.md
- .github/renovate.json
- examples/docker-compose/docker-compose.yaml
- examples/docker-compose/package.json
- examples/docker-compose/test/docker-compose.test.ts
- pnpm-lock.yaml
- enable renovate for `docker-compose`
- create e2e tests for the docker-compose example. Among other things it will ensure renovate bumps are tested against CI
- use the default health checks from the services
- do not use `latest` tags so we are sure the docker-compose example works for the given versions of the services
> chore: improve docker-compose example

- .github/workflows/ci.yaml
Same logic tested in [hasura-auth](https://github.com/nhost/hasura-auth/actions/runs/3610387312).
`e2e: @nhost-examples/react-apollo` is harder to read than `e2e: examples/react-apollo`, especially with folded names in the GH action recap.
> ci: improve the names of the e2e matrix jobs

- .github/workflows/ci.yaml
- .npmrc
- pnpm-lock.yaml
- correct the lock file in order to use the packages present in the workspace instead of the npm registry
- add the `prefer-workspace-packages` option to `.npmrc` so Renovate will (hopefully) generate the lockfile accordingly
- force all e2e to run in CI when the lock file changed
> fix: use workspace to resolve internal dependencies

- .changeset/rude-singers-carry.md
- dashboard/src/components/settings/signInMethods/WindowsLiveProviderSettings/WindowsLiveProviderSettings.tsx
In the Nhost dashboard for signed in client, the callback url for windows live/microsoft option is shown incorrectly. Should show "/windowslive/callback" versus "/microsoft/callback"
> Windows Live Provider displayed link updated to match backend url

- dashboard/CHANGELOG.md
- dashboard/package.json
- dashboard/src/components/overview/OverviewProjectInfo/OverviewProjectInfo.tsx
This is a follow-up PR for https://github.com/nhost/nhost/issues/1370.
> fix(dashboard): don't break the UI when project is not loaded yet

- .changeset/config.json
- .changeset/empty-wolves-exercise.md
- .changeset/rotten-flowers-hope.md
- .changeset/twenty-toes-jump.md
- dashboard/src/components/settings/environmentVariables/SystemEnvironmentVariableSettings/SystemEnvironmentVariableSettings.tsx
- dashboard/src/hooks/useAppClient.ts
- docs/docs/quickstarts/nextjs.mdx
- docs/docs/reference/nextjs/index.mdx
- examples/nextjs/components/protected-route.tsx
- examples/nextjs/pages/_app.tsx
- packages/hasura-auth-js/src/hasura-auth-client.ts
- packages/hasura-auth-js/src/internal-client.ts
- packages/hasura-auth-js/src/machines/authentication/machine.ts
- packages/hasura-auth-js/src/machines/authentication/machine.typegen.ts
- packages/hasura-auth-js/src/types/client.ts
- packages/hasura-auth-js/tests/changeEmail.test.ts
- packages/hasura-auth-js/tests/changePassword.test.ts
- packages/hasura-auth-js/tests/enableMfa.test.ts
- packages/nextjs/src/get-session.ts
- packages/nextjs/src/index.ts
- packages/nhost-js/src/clients/nhost.ts
- packages/react/package.json
- packages/react/src/provider.tsx
- packages/vue/package.json
- pnpm-lock.yaml
Extracted from the `sdk-next-major` branch. Initial PR: #1298
- iron up the start of the auth client
- simplify `onAuthStateChanged` and `onTokenChanged`
- avoid creating inconsistent states when using React 18 strict mode (components are rendered twice) 
- fix: when rendering a SSR page, do not call a token refresh on the client side as the session has been hydrated by the server 
- get rid of the `immer` dependency
- [link packages in changesets](https://github.com/changesets/changesets/blob/main/docs/linked-packages.md)
> fix: React 18 strict mode and other improvements

- examples/docker-compose/test/docker-compose.test.ts
The Docker-compose tests occasionally fail in CI when Traefik is ready, but the underlying service isn't.
This PR should avoid this in waiting up to a minute for the service to be healthy.
> test(docker-compose): more retries

- .github/actions/nhost-cli/action.yaml
Since a week or two, the installation of the CLI often fails on CI.
Unless there is a clearer explanation on why it occurs, this "retry" logic will (hopefully) overcome the problem
> ci: retry the Nhost CLI installation

- .github/workflows/renovate.yaml
When a Renovate PR is merged, the `Renovate` workflow was trying to push a changeset to `main`. But as `main` is protected, it was failing until now.
This change does not try to push to main anymore, but instead create a pull request that is flagged to `auto-merge`, and is automatically approved.
> ci: create renovate changeset pr

- .changeset/unrepeatable-expenditure-blackshirt.md
This PR creates the changesets from the Renovate dependencies that have been merged to main.
> chore: create changesest from Renovate bumps

- .github/renovate.json
- ignore `@types/node` as we force the repository to work with Node 16
- explicit list of enabled managers in order to enable `docker-compose`
> ci: improve renovate configuration

- .changeset/wise-buses-pay.md
- dashboard/src/components/dashboard/AccountMenu.tsx
Right now, when signing out you get an error regarding a missing field in our cache `workspace_members` this is because we sign out the user with `nhost.auth.signOut();` prior to redirecting and when we query again for the workspace the user has, it comes out as null (as there is no user) and then redirect.
> fix(dashboard): Resetting the cache when signing out.

- .changeset/wet-berries-smell.md
- packages/nextjs/src/create-server-side-client.ts
- packages/nextjs/src/index.ts
- packages/nextjs/src/utils.ts
Store the session in a cookie so there is no need for an SSR page to ask for a new access token
Closes https://github.com/nhost/nhost/issues/1336
> chore: store the session in a cookie to avoid refetching the jwt on every ssr call

- .changeset/odd-roses-hug.md
- examples/react-apollo/cypress/support/e2e.ts
- examples/vue-apollo/src/components/ErrorSnackBar.vue
- packages/react/src/client.ts
- packages/react/src/index.ts
- packages/vue/src/client.ts
`BackendUrl`, `ErrorPayload`, `NhostSession`, `Subdomain`, and `User` are now exported in all our SDKs
> Export commonly used types

- .changeset/lovely-ants-provide.md
- dashboard/src/components/common/ControlledAutocomplete/ControlledAutocomplete.tsx
- dashboard/src/components/dataBrowser/BaseColumnForm/BaseColumnForm.tsx
- dashboard/src/components/dataBrowser/BaseTableForm/BaseTableForm.tsx
- dashboard/src/components/dataBrowser/BaseTableForm/ColumnEditorRow.tsx
- dashboard/src/components/dataBrowser/EditPermissionsForm/sections/ColumnPresetsSection.tsx
- dashboard/src/hooks/dataBrowser/useTrackForeignKeyRelationsMutation/prepareTrackForeignKeyRelationsMetadata.test.ts
- dashboard/src/hooks/dataBrowser/useTrackForeignKeyRelationsMutation/prepareTrackForeignKeyRelationsMetadata.ts
- dashboard/src/hooks/dataBrowser/useUpdateTableMutation/prepareUpdateTableQuery.ts
Don't break table creation when referencing a table which is not in the `public` schema.
This PR also fixes a few other Database UI-related issues such as disabling the unnecessary `autoComplete` property on input fields, therefore, making the editing process much easier.
Thanks @timpratim for your report 🙌🏼
> fix(dashboard): don't break the table creation process

- dashboard/Dockerfile
- pnpm-lock.yaml
- pnpm-workspace.yaml
`dashboard/Dockerfile` installs turborepo without specifying the version (hence `latest`), and it therefore installs the new version `1.7.0` that has been released yesterday.
For some reason this version behaves differently and makes a workspace check when running `turbo prune`. And our `pnpm-workspace.yaml`  was not excluding the `**/functions` packages, which were all named `functions` -> error.
> chore: exclude functions from workspace

- .changeset/old-wasps-yell.md
- examples/react-apollo/cypress.config.ts
- packages/hasura-auth-js/src/constants.ts
- packages/hasura-auth-js/src/machines/authentication/machine.ts
- packages/hasura-auth-js/tests/refreshToken.test.ts
Set limits to refreshing the token on error
When starting, the client was trying to refresh the token five times every second, then indefinitely every five seconds.
It is now limited to 5 attempts at the following intervals: 5, 10, 20, 40, and 80 seconds. If all these attempts fail, the user state is signed out.
Similarly, when refreshing the token failed, the client attempted to refresh the token every second.
It is now limited to 5 attempts at the following intervals: 5, 10, 20, 40, and 80 seconds.
> exponential backoff

- .changeset/many-rocks-relax.md
- .changeset/six-horses-ring.md
- .changeset/wise-shoes-smoke.md
- dashboard/package.json
- dashboard/src/components/applications/AppDeployments.tsx
- dashboard/src/components/applications/ApplicationLive.tsx
- dashboard/src/components/deployments/DeploymentListItem/DeploymentListItem.tsx
- dashboard/src/components/overview/OverviewDeployments/OverviewDeployments.test.tsx
- dashboard/src/components/overview/OverviewDeployments/OverviewDeployments.tsx
- dashboard/src/components/ui/Avatar.tsx
- dashboard/src/components/ui/v2/ActivityIndicator/ActivityIndicator.tsx
- dashboard/src/context/workspace1-context.tsx
- dashboard/src/hooks/dataBrowser/useManagePermissionMutation/managePermission.test.ts
- dashboard/src/utils/helpers.ts
- dashboard/src/utils/testUtils.tsx
- integrations/apollo/package.json
- integrations/apollo/src/index.ts
- packages/hasura-auth-js/package.json
- pnpm-lock.yaml
https://discord.com/channels/552499021260914688/1072550304828096614/1072550304828096614
The dashboard was not properly handling the scenario where no deployments were returned by the server. For instance, if the user left the page idle for an extended period and then opened it again, no data would be returned by the subscription, causing the dashboard to break.
This PR fixes the issue with the dashboard and ensures that it handles the case where no deployments are returned by the server. Additionally, we have included a patch bump for `@nhost/apollo`. The new version includes an option to configure the link attribute of the underlying `ApolloClient`. This feature is particularly useful in scenarios where you need to override the client's default behavior, such as in a test environment.
> fix(dashboard): don't break the UI when deployments are unavailable

- .changeset/silver-kings-attack.md
- dashboard/src/components/common/ControlledAutocomplete/ControlledAutocomplete.tsx
- dashboard/src/components/dataBrowser/DataBrowserSidebar/DataBrowserSidebar.tsx
- dashboard/src/components/dataBrowser/EditPermissionsForm/RolePermissionEditorForm.tsx
- dashboard/src/components/dataBrowser/EditPermissionsForm/sections/RowPermissionsSection.tsx
- dashboard/src/components/dataBrowser/EditPermissionsForm/validationSchemas.ts
- dashboard/src/components/dataBrowser/RuleGroupEditor/RuleValueInput.tsx
- dashboard/src/components/ui/v2/Autocomplete/Autocomplete.tsx
fixes #1555
Additional fixes:
- Blurring the "Limit" input field resulted in a validation error
- Permission rule editor didn't accept number inputs (I thought Hasura converts numbers to strings, but it didn't)
> fix(dashboard): allow permission editing for auth and storage schemas

- docs/docs/authentication/sign-in-methods/4-google.mdx
The guide was missing a step - you also have to fill out the JavaScript origins with your Nhost URI otherwise you get a 404 error when authenticating.
> Added Javascript origins step to docs

- .changeset/odd-dots-end.md
- docs/docs/serverless-functions.mdx
Based on https://github.com/nhost/nhost/discussions/1752#discussioncomment-5380702 adding a link so users know to look at the other section for more information on configuring functions.
> Update serverless-functions to link to event trigger docs

- .changeset/healthy-seals-argue.md
- .changeset/odd-rocks-sort.md
- packages/nhost-js/src/clients/functions/index.ts
- packages/nhost-js/src/clients/functions/types.ts
- packages/nhost-js/src/utils/types.ts
- packages/vue/src/useError.ts
Error messages coming from serverless functions were suppressed by the SDK.
See this discussion for more information: https://discord.com/channels/552499021260914688/1095126695197016117
Fixes #1832
> fix(nhost-js): don't suppress error messages

- .changeset/green-kangaroos-wait.md
- integrations/apollo/src/index.ts
Some background: We are using nhost to develop a react-native app.
The issue we are having is that when we go back to the app after the token has been expired and a query is fired before nhost auth handles a token refresh, that query obviously fail.
This is the way I solved the issue. Maybe there's a nicer way to do it, maybe subscribing to token changes is better? Feedback is welcome if you have any ideas. But this should ensure that the connection waits to be established until we have a valid token (or are signed out).
Just threw this together now. Will test how it works for our issue tomorrow.
Update: works great for us and we don't have the issue anymore
> Wait for valid token or sign out before establishing connection.

- docs/docs/authentication/index.mdx
On the docs page describing login methods [`Security Keys (WebAuthn)`](https://docs.nhost.io/authentication/sign-in-methods) is linking to `/authentication/sign-in-with-phone-number-sms`, however it should be linking to `/authentication/sign-in-methods`.
This PR fixes that.
> Fixed linking to wrong destination in docs

- .github/workflows/changesets.yaml
I've deleted almost all the cache, and now we just need this to run successfully without a timeout to be able to write a new cache
> chore: increase timeout for Publish to Docker Hub

- .changeset/violet-onions-swim.md
- integrations/apollo/src/index.ts
> fix: integrations: apollo: set accessToken to null after TOKEN_CHANGED event on sign-out

- .changeset/fuzzy-wasps-breathe.md
- packages/react/src/useChangeEmail.ts
- packages/vue/src/useChangeEmail.ts
The example provided in docs has been modified from;
```
await changeEmail({
email: 'new@example.com'
})
```
to;
`await changeEmail('new@example.com')`
> Update Docs for useChangeEmail.ts Example

- .changeset/breezy-pugs-wash.md
- packages/nhost-js/src/index.ts
- packages/nhost-js/src/utils/helpers.ts
There are many cases when it would be useful to construct the default nhost URLs and it would be helpful to be able to use the existing urlFromSubdomain helper instead of cobbling together the URLs from scratch. One example would be when using a custom auth domain and needing to switch to init the client with serviceUrls but needing to keep the other URLs as default.
> feat: export urlFromSubdomain helper

- .changeset/six-spies-tie.md
- examples/react-apollo/nhost/nhost.toml
- examples/react-apollo/src/components/OauthLinks.tsx
- needs this [PR](https://github.com/nhost/hasura-auth/pull/438) merged and the latest version of `hasura-auth`
- related to this https://github.com/nhost/nhost/issues/2364
- fixes this https://github.com/nhost/projects/issues/43
> feat(examples): add sign-in with Linked to react-apollo

- .changeset/rare-fans-marry.md
- docs/docs/authentication/sign-in-methods/4-linkedin.mdx
> fix(docs): add instructions for enabling Sign In with LinkedIn using OpenID Connect

- examples/quickstarts/nhost-backend/nhost/metadata/databases/default/tables/storage_virus.yaml
- examples/quickstarts/nhost-backend/nhost/metadata/databases/default/tables/tables.yaml
- This is mainly for consistency
- Does not need a changeset
> chore(quickstarts): add virus table metadata

- examples/quickstarts/sveltekit/package.json
This will ensure CI doesn't complain about trying to install an unpublished version of the @nhost/nhost-js package in the SvelteKit quickstart.
> fix(ci): pin `@nhost/nhost-js` dep version in sveltekit quickstart

- .changeset/clever-pigs-end.md
- examples/docker-compose/README.md
Add extended explanation as to why `hasura-console` needs to be run locally. Right now it's confusing to the user why editing is not possible just with the Hasura Docker container.
> chore (examples/docker-compose): update README.md to explain why hasura-console is needed

- .changeset/ninety-deers-whisper.md
- packages/vue/src/client.ts
fixes https://github.com/nhost/nhost/issues/2134
> fix(vue-sdk): include `ServiceUrls` in `NhostVueClientConstructorParams`

- .changeset/poor-panthers-shout.md
- packages/hasura-auth-js/package.json
- packages/hasura-auth-js/src/hasura-auth-client.ts
- pnpm-lock.yaml
fixes https://github.com/nhost/nhost/issues/2513
> fix(hasura-auth-js): use `jose` instead of `jwt-decode` to decode the accessToken and get the Hasura claims

- .changeset/afraid-ducks-hang.md
- examples/docker-compose/README.md
Should answer questions like these: https://discord.com/channels/552499021260914688/1212064280170463243
> chore (examples/docker-compose): clarification on greyed-out options in the dashboard when self-hosting

- .changeset/spicy-trains-trade.md
- packages/graphql-js/src/client.ts
- packages/hasura-storage-js/src/hasura-storage-api.ts
- packages/hasura-storage-js/src/hasura-storage-client.ts
- packages/hasura-storage-js/src/utils/types.ts
- packages/nhost-js/src/clients/functions/index.ts
- packages/nhost-js/src/clients/nhost.ts
resolves https://github.com/nhost/nhost/issues/2696
> feat: sdk: add `setHeaders` for setting global headers and make sure all client calls have a `headers` arg

- .changeset/plenty-beers-warn.md
- packages/hasura-auth-js/src/utils/environment.ts
fix https://github.com/nhost/nhost/issues/2216
> fix(hasura-auth-js): resolve social sign-in issue in React Native

- .changeset/real-pens-fly.md
- examples/quickstarts/nextjs-server-components/src/utils/nhost.ts
fixes https://github.com/nhost/nhost/issues/2742
___
Bug fix, Documentation
___
- Disabled `autoRefreshToken` in the server-side configuration of `NhostClient` to fix an issue.
- Added a changeset to document the fix.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>nhost.ts</strong><dd><code>Disable autoRefreshToken in server-side NhostClient configuration</code></dd></summary>
<hr>
examples/quickstarts/nextjs-server-components/src/utils/nhost.ts
<li>Disabled <code>autoRefreshToken</code> when running server side.<br> <li> Added <code>autoRefreshToken: false</code> to <code>NhostClient</code> configuration.<br>
</details>
</td>
<td><a …
> fix: quickstarts: next-js-server-components: disable `autoRefreshToken` when running nhost-js server side

- .changeset/twenty-starfishes-kiss.md
- docs/guides/functions/runtimes.mdx
Documentation
___
- Added `pnpm` to the list of supported package managers for Node.js functions in the documentation.
- Updated the guide to include `pnpm-lock.yaml` and clarified the precedence order of lockfiles.
- Added a changeset entry for the documentation update.
___
<tr>
<td>
<details>
<summary><strong>twenty-starfishes-kiss.md</strong><dd><code>Add changeset entry for pnpm support in docs</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.changeset/twenty-starfishes-kiss.md
- Added a changeset entry for the documentation update.
</details>
</td>
<td><a …
> chore (docs): add pnpm to list of supported packagers for functions

- .changeset/honest-humans-explode.md
- dashboard/src/features/projects/common/components/ApplicationLockedReason/ApplicationLockedReason.tsx
Adds redirect to `/support` page when clicking on contact support on locked project screen
> chore (dashboard): locked project contact support redirect

- .changeset/long-plums-shave.md
- dashboard/src/features/services/components/ServiceForm/ServiceForm.tsx
- dashboard/src/features/services/components/ServiceForm/components/ServiceDetailsDialog/ServiceDetailsDialog.tsx
___
- Removed the `subdomain` prop from the `ServiceDetailsDialog` component and its usage in `ServiceForm`.
- Updated `ServiceDetailsDialog` to use `currentProject?.subdomain` directly.
- Added a changeset file documenting the fix.
___
<tr>
<td>
<details>
<summary><strong>ServiceForm.tsx</strong><dd><code>Remove `subdomain` prop from `ServiceDetailsDialog` usage</code></dd></summary>
<hr>
dashboard/src/features/services/components/ServiceForm/ServiceForm.tsx
<li>Removed the <code>subdomain</code> prop from <code>ServiceDetailsDialog</code> component.<br> <li> Updated the <code>ServiceDetailsDialog</code> component usage.<br> …
> fix: use current project subdomain in ServiceDetailsDialog component

- .changeset/clever-hats-roll.md
- dashboard/src/features/services/components/ServiceForm/ServiceForm.tsx
- dashboard/src/features/services/components/ServiceForm/components/PortsFormSection/PortsFormSection.tsx
- dashboard/src/features/services/components/ServiceForm/components/ServiceDetailsDialog/ServiceDetailsDialog.tsx
___
- Added `subdomain` prop to `ServiceDetailsDialog` component and its interface.
- Updated `ServiceForm` to pass `subdomain` to `ServiceDetailsDialog`.
- Changed subdomain source from `currentProject` to `formValues` in `PortsFormSection` URL generation.
- Added a changeset for the fix.
___
<tr>
<td>
<details>
<summary><strong>ServiceForm.tsx</strong><dd><code>Pass subdomain to ServiceDetailsDialog in ServiceForm</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/features/services/components/ServiceForm/ServiceForm.tsx
- Added `subdomain` prop to `ServiceDetailsDialog` component.
</details>
</td>
<td><a …
> fix(dashboard): use service subdomain in service form and service details dialog

- .changeset/silent-lies-smoke.md
- audit-ci.jsonc
- dashboard/global-teardown.ts
- packages/hasura-auth-js/src/machines/authentication/machine.ts
- packages/hasura-auth-js/src/machines/authentication/machine.typegen.ts
- packages/hasura-auth-js/tests/refreshToken.test.ts
fixes https://github.com/nhost/nhost/issues/2817
___
Bug fix, Tests, Enhancement
___
- Added error handling logic to transition to the `signedOut` state when the token is invalid or expired.
- Updated the authentication machine to handle 401 errors by signing out the user.
- Enhanced test cases to verify the new behavior of signing out on unauthorized errors.
- Updated Hasura page teardown logic to ensure the first matching element is clicked.
- Added `micromatch` to the audit-ci allowlist for dependency management.
___
<tr>
<td>
<details>
<summary><strong>machine.ts</strong><dd><code>Add error handling for unauthorized token refresh</code>&nbsp; &nbsp; …
> fix(hasura-auth-js): transition to the `signedOut` state when the token is invalid or expired

- .changeset/popular-rabbits-bake.md
- packages/hasura-auth-js/src/machines/authentication/machine.ts
- packages/hasura-auth-js/src/machines/authentication/machine.typegen.ts
fixes https://github.com/nhost/nhost/issues/2836
___
___
- Enhanced the signout process to utilize the access token when clearing all sessions.
- Updated the `signingOut` state to manage both access and refresh tokens.
- Introduced a new function `destroyAccessToken` to clear the access token.
- Adjusted type definitions to reflect changes in the signout process.
- Added a changeset document to outline the patch changes.
___
<tr>
<td>
<details>
<summary><strong>machine.ts</strong><dd><code>Enhance signout process to handle access token</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
> fix(hasura-auth-js): update signout to use accessToken when clearing all sessions

- .changeset/grumpy-toys-love.md
- dashboard/src/features/services/components/ServiceForm/components/ComputeFormSection/ComputeFormSection.tsx
- dashboard/src/features/services/components/ServiceForm/components/ReplicasFormSection/ReplicasFormSection.tsx
Fixes #2885
___
___
- Updated documentation URLs in both ComputeFormSection and ReplicasFormSection components from 'https://docs.nhost.io/run/resources' to 'https://docs.nhost.io/guides/run/resources'
___
<tr>
<td>
<details>
<summary><strong>ComputeFormSection.tsx</strong><dd><code>Update docs URL and minor styling adjustments</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/features/services/components/ServiceForm/components/ComputeFormSection/ComputeFormSection.tsx
<li>Updated URL for documentation link from <br>'https://docs.nhost.io/run/resources' to …
> fix (dashboard): update url to docs in run services tooltip

- .changeset/purple-vans-protect.md
- dashboard/src/components/ui/v2/ErrorToast/ErrorToast.tsx
Fixes #2887
___
___
- Fixed issue with long error messages overflowing in the error toast component
- Improved layout and responsiveness of the error toast:
- Added text ellipsis for long messages
- Ensured buttons maintain their size with flex-shrink-0
- Adjusted spacing and flex properties for better alignment
- Changed error message container from <span> to <p> for better semantics
- Added a changeset to document the fix and specify a minor version bump
___
<tr>
<td>
<details>
<summary><strong>ErrorToast.tsx</strong><dd><code>Improve error toast layout and text overflow handling</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
> fix (dashboard): long error message in error toast overflow

- dashboard/src/features/projects/overview/components/OverviewTopBar/OverviewTopBar.tsx
Enhancement
___
- Simplified the logic for displaying the project migration button in the OverviewTopBar component
- Removed the check for 'Pro' plan, allowing all project owners to see the migration option regardless of their plan
- This change makes the migration feature more accessible to all project owners
___
<tr>
<td>
<details>
<summary><strong>OverviewTopBar.tsx</strong><dd><code>Simplify project migration button visibility</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/features/projects/overview/components/OverviewTopBar/OverviewTopBar.tsx
<li>Removed the …
> fix workspace migrate button

- dashboard/src/features/projects/common/hooks/useNotFoundRedirect/useNotFoundRedirect.ts
Bug fix
___
- Fixed the `useNotFoundRedirect` hook to exclude the `/account` path from being redirected to the 404 page.
___
<tr>
<td>
<details>
<summary><strong>useNotFoundRedirect.ts</strong><dd><code>Exclude `/account` path from 404 redirection</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/features/projects/common/hooks/useNotFoundRedirect/useNotFoundRedirect.ts
<li>Added a condition to exclude the <code>/account</code> path from the 404 <br>redirection logic.<br>
</details>
</td>
<td><a href="https://github.com/nhost/nhost/pull/2935/files#diff-837279cf43199053bca09913f62c …
> fix useNotFoundRedirect to exclude /account path

- .changeset/violet-teachers-agree.md
- .github/workflows/changesets.yaml
- dashboard/src/features/orgs/components/MigrateProjectToOrg/MigrateProjectToOrg.tsx
- dashboard/src/features/orgs/projects/resources/settings/components/ResourcesConfirmationDialog/ResourcesConfirmationDialog.tsx
- dashboard/src/features/orgs/projects/resources/settings/components/ResourcesForm/ResourcesForm.test.tsx
- dashboard/src/features/orgs/projects/resources/settings/components/ResourcesForm/ResourcesForm.tsx
- dashboard/src/features/orgs/projects/resources/settings/components/ResourcesForm/ResourcesFormFooter.tsx
- dashboard/src/features/orgs/projects/resources/settings/components/ServiceResourcesFormFragment/ServiceResourcesFormFragment.tsx
- dashboard/src/features/orgs/projects/resources/settings/utils/resourceSettingsValidationSchema/resourceSettingsValidationSchema.ts
- dashboard/src/tests/orgs/mocks.ts
- package.json
- pnpm-lock.yaml
- templates/cra-template-nhost-react-apollo-template/template/package-lock.json
fixes https://github.com/nhost/nhost/issues/2939
___
Enhancement, Bug fix
___
- Reset the form state when the migration dialog is opened or closed to ensure a clean state.
- Disable the 'Migrate' button if the form is not dirty to prevent submission without changes.
- Ensure the 'Cancel' button also resets the form state to avoid unintended data retention.
___
<tr>
<td>
<details>
<summary><strong>MigrateProjectToOrg.tsx</strong><dd><code>Improve form handling and validation in migration modal</code>&nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/features/orgs/components/MigrateProjectToOrg/MigrateProjectToOrg.tsx
<li>Reset form state when dialog is …
> fix: disable migrate project submit button when form is not dirty

- dashboard/src/pages/support/ticket.tsx
Enhancement
___
- Added support for selecting an organization in the support ticket form.
- Modified the form validation schema to include the organization field.
- Updated the logic to fetch and handle organizations data.
- Adjusted the UI layout to accommodate the new organization selection.
___
<tr>
<td>
<details>
<summary><strong>ticket.tsx</strong><dd><code>Add organization selection to support ticket form</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/pages/support/ticket.tsx
<li>Added support for selecting an organization in the support ticket <br>form.<br> <li> Modified the form validation schema …
> feat: dashboard: add org to support ticket

- .changeset/fresh-clouds-roll.md
- docs/development/cli/getting-started.mdx
Removed '>' in commands for nhost CLI installation. 
This way if you click the copy to clipboard button you can paste and run the command directly (you don't have to erase the '>' prepended)
> fix (docs): update commands in nhost cli quickstart

- pnpm-lock.yaml
- templates/react-native/package.json
- templates/react-native/template/package.json
___
- Added `react-dom` dependency to the React Native template to resolve dependency issues.
- Ensured compatibility between `react` and `react-dom` versions.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Add `react-dom` dependency to React Native template</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/react-native/template/package.json
<li>Added <code>react-dom</code> dependency with version <code>18.2.0</code>.<br> <li> Ensured compatibility with <code>react</code> version <code>18.2.0</code>.<br>
</details>
</td>
<td><a …
> fix(templates/react-native): resolve dependency issue with `react-dom` in react-native example

- .changeset/poor-kangaroos-know.md
- packages/hasura-auth-js/src/hasura-auth-client.ts
- packages/hasura-auth-js/src/internal-client.ts
- packages/hasura-auth-js/src/machines/authentication/machine.ts
- packages/hasura-auth-js/src/types/client.ts
- packages/nhost-js/src/clients/auth.ts
- packages/nhost-js/src/clients/nhost.ts
- packages/nhost-js/src/utils/types.ts
Fixes https://github.com/nhost/nhost/issues/3019
___
___
- Added `broadcastKey` parameter to `HasuraAuthClient`, `AuthClient`, and `createAuthMachine` constructors to ensure unique keys for synchronizing authentication state across browser tabs.
- Modified `BroadcastChannel` initialization to use the new `broadcastKey` parameter.
- Updated `NhostClientConstructorParams` to omit `broadcastKey`.
- Added changeset documentation for the new `broadcastKey` feature.
___
<tr>
<td>
<details>
<summary><strong>hasura-auth-client.ts</strong><dd><code>Add `broadcastKey` parameter to `HasuraAuthClient` constructor</code></dd></summary>
<hr> …
> fix(hasura-auth-js, nhost-js): use a unique `broadcastKey` per nhost client for synchronizing authentication state across browser tabs

- .changeset/strange-poems-live.md
- dashboard/src/features/orgs/components/billing/components/BillingEstimate/components/Estimate/Estimate.tsx
Bug fix, Other
___
- Fixed the billing estimate calculation by removing the check for `amount` being falsy and directly checking if `amount` is not a number.
- Added a changeset entry to document the fix.
___
<tr>
<td>
<details>
<summary><strong>Estimate.tsx</strong><dd><code>Fix billing estimate calculation when amount due is zero</code>&nbsp; </dd></summary>
<hr>
dashboard/src/features/orgs/components/billing/components/BillingEstimate/components/Estimate/Estimate.tsx
<li>Removed check for <code>amount</code> being falsy before returning 'N/A'.<br> <li> Simplified the logic to directly check if <code>amount</code> is not a number.<br>
</details>
</td> …
> fix (dashboard): correct billing estimate when amount due is zero

- .github/workflows/changesets.yaml
- .github/workflows/deploy-dashboard.yaml
enhancement, configuration changes
___
- Consolidated Vercel deployment steps into a reusable workflow to simplify the `publish-vercel` job.
- Replaced inline steps with a call to `deploy-dashboard.yaml`, passing necessary parameters and inheriting secrets.
___
<tr>
<td>
<details>
<summary><strong>changesets.yaml</strong><dd><code>Consolidate Vercel deployment steps into reusable workflow</code></dd></summary>
<hr>
.github/workflows/changesets.yaml
<li>Replaced inline Vercel deployment steps with a reusable workflow.<br> <li> Simplified the <code>publish-vercel</code> job by using <code>deploy-dashboard.yaml</code>.<br> <li> Inherited secrets and passed …
> chore: consolidate Vercel deployment steps into reusable workflow

- .changeset/thirty-sloths-collect.md
- dashboard/src/features/orgs/projects/database/dataGrid/hooks/useUpdateColumnMutation/useUpdateColumnMutation.ts
- dashboard/src/features/orgs/projects/database/dataGrid/hooks/useUpdateRecordMutation/useUpdateRecordMutation.ts
Bug fix, Other
___
- Replaced the `useCurrentWorkspaceAndProject` hook with the `useProject` hook to ensure the correct project data is used when editing a table cell.
- Updated the logic to use the new project hook for generating the app URL and retrieving the admin secret.
- Added a changeset file to document the fix.
___
<tr>
<td>
<details>
<summary><strong>useUpdateRecordMutation.ts</strong><dd><code>Update project hook usage in record mutation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/features/orgs/projects/database/dataGrid/hooks/useUpdateRecordMutation/useUpdateRec …
> fix(dashboard): use correct project hook when editing table cell

- package.json
- pnpm-lock.yaml
enhancement, dependencies
___
- Updated the `prettier` dependency in `package.json` from version `^2.8.8` to `^3.3.3` to address issues with changeset changelog formatting.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update Prettier version in package.json</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<li>Updated the <code>prettier</code> dependency version from <code>^2.8.8</code> to <code>^3.3.3</code>.<br>
</details>
</td>
<td><a href="https://github.com/nhost/nhost/pull/3059/files#diff-7ae45ad102eab3b6d7e7 …
> fix: update prettier version to fix changeset changelog

- .changeset/khaki-pets-argue.md
- dashboard/src/features/orgs/projects/overview/components/OverviewMetrics/OverviewMetrics.tsx
- dashboard/src/gql/app/getProjectMetrics.gql
- dashboard/src/gql/app/getProjectRequestsMetric.gql
- dashboard/src/gql/organizations/getUserProjectMetrics.gql
- dashboard/src/utils/__generated__/graphql.ts
resolves https://github.com/nhost/nhost/issues/3017
___
Enhancement, Other
___
- Introduced new metrics in the dashboard overview, including monthly and daily active users, total users, and storage.
- Implemented a new GraphQL query `GetUserProjectMetrics` to fetch user-related metrics.
- Updated the `OverviewMetrics` component to display the newly added metrics.
- Enhanced the GraphQL schema with new fields and queries to support the additional metrics.
- Added a changeset to document the new feature in the dashboard.
___
<tr>
<td>
<details>
<summary><strong>OverviewMetrics.tsx</strong><dd><code>Add support for additional user and storage metrics in …
> feat(dashboard): add support for additional metrics in overview

- .github/workflows/gen_ai_review.yaml
enhancement
___
- Removed the 'contents: write' permission from the GitHub Actions workflow to enhance security by limiting permissions to only those necessary for the job.
- The change ensures that the workflow runs with minimal permissions, reducing potential security risks.
___
<tr>
<td>
<details>
<summary><strong>gen_ai_review.yaml</strong><dd><code>Remove unnecessary permissions from GitHub Actions workflow</code></dd></summary>
<hr>
.github/workflows/gen_ai_review.yaml
<li>Removed 'contents: write' permission from the workflow.<br> <li> Ensured only necessary permissions are retained for the job.<br>
</details>
</td>
<td><a …
> chore (ci): remove unnecessary/unsafe permissions to gen_ai_review

- .changeset/stale-avocados-shake.md
- dashboard/src/features/orgs/hooks/useRemoteApplicationGQLClient/useRemoteApplicationGQLClient.tsx
- dashboard/src/features/orgs/projects/graphql/common/hooks/useGetAppUsers.ts
- dashboard/src/features/orgs/projects/hooks/useAppClient/useAppClient.ts
- dashboard/src/features/orgs/projects/hooks/useProject/useProject.ts
- dashboard/src/features/orgs/projects/storage/dataGrid/components/DataGridPreviewCell/DataGridPreviewCell.tsx
- dashboard/src/features/orgs/projects/storage/dataGrid/components/FilesDataGrid/FilesDataGrid.tsx
- dashboard/src/features/orgs/projects/storage/dataGrid/components/FilesDataGridControls/FilesDataGridControls.tsx
- dashboard/src/features/orgs/projects/storage/dataGrid/hooks/useFiles/useFiles.ts
- dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/graphql.tsx
___
- Removed the `target` option from multiple `useProject` hook calls across various components to simplify usage.
- Enhanced the `useProject` hook by improving project fetching logic with `useMemo` and adjusting refetching and caching strategies.
- Made minor formatting adjustments in several files for consistency.
- Added a changeset documenting the improvements in project polling logic.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>9 files</summary><table>
<tr>
<td>
<details>
<summary><strong>useRemoteApplicationGQLClient.tsx</strong><dd><code>Simplified `useProject` hook usage by removing `target` option</code></dd></summary>
<hr> …
> fix: improve`useProject` hook to use proper caching and refetching

- .changeset/purple-trains-itch.md
- dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/settings/index.tsx
Resolves #3048
___
Enhancement
___
- Added a warning message when pausing a project with Run services that have persistent volume data.
- The warning is displayed in an Alert component within the pause confirmation dialog.
- Implemented logic to determine when to show the warning based on the project's plan and Run services configuration.
- Updated the pause confirmation dialog to include more detailed information and styling.
- Added a changeset file to document the minor version bump for this feature.
___
<tr>
<td>
<details>
<summary><strong>index.tsx</strong><dd><code>Add warning for Run service data loss on project pause</code>&nbsp; &nbsp; &nbsp; …
> chore (dashboard): warn run volumes losing data on project pause

- .changeset/eighty-candles-tell.md
- dashboard/src/features/orgs/projects/resources/settings/components/ResourcesForm/ResourcesForm.tsx
- dashboard/src/features/orgs/projects/resources/settings/components/ServiceResourcesFormFragment/ServiceResourcesFormFragment.tsx
- dashboard/src/features/orgs/projects/resources/settings/gql/getResources.gql
- dashboard/src/utils/__generated__/graphql.ts
Fixes #3075
___
___
- Fixed a bug that prevented removing compute resources when PostgreSQL capacity was higher than 10
- Refactored resource configuration handling to preserve non-compute settings when disabling resources
- Updated GraphQL types and queries to include additional fields for networking and storage configurations
- Implemented UI tweaks for better alignment and dark theme compatibility in the resource settings form
- Added a changeset file to document the bug fix and minor version bump
___
<tr>
<td>
<details>
<summary><strong>ResourcesForm.tsx</strong><dd><code>Refactor resource configuration handling</code>&nbsp; …
> fix (dashboard): remove compute resources erases postgres capacity

- .changeset/flat-apes-shake.md
- .changeset/long-guests-sparkle.md
- examples/quickstarts/nextjs-server-components/package.json
- examples/quickstarts/nextjs-server-components/src/utils/nhost.ts
- packages/hasura-auth-js/src/hasura-auth-client.ts
- pnpm-lock.yaml
resolves https://github.com/nhost/nhost/issues/2319
___
Enhancement
___
- Added new `initWithSession()` method to `@nhost/hasura-auth-js` package, allowing initialization of auth client with an existing session
- Simplified Nhost client initialization in Next.js server components example by using the new `initWithSession()` method
- Removed xstate dependency from Next.js server components example
- Updated changesets to document the new feature and changes in the Next.js example
- Improved code organization and reduced complexity in the Next.js example
___
<tr>
<td>
<details>
<summary><strong>nhost.ts</strong><dd><code>Simplify Nhost client initialization …
> feat(hasura-auth-js): feat: add`initWithSession` to initialize auth client with existing session

- .changeset/shy-geckos-switch.md
- dashboard/src/features/orgs/projects/common/hooks/useProjectRedirectWhenReady/useProjectRedirectWhenReady.ts
- dashboard/src/features/orgs/projects/database/settings/components/DatabaseConnectionInfo/DatabaseConnectionInfo.tsx
- dashboard/src/features/orgs/projects/database/settings/components/DatabaseServiceVersionSettings/DatabaseServiceVersionSettings.tsx
- dashboard/src/features/orgs/projects/database/settings/components/DatabaseStorageCapacity/DatabaseStorageCapacity.tsx
- dashboard/src/features/orgs/projects/database/settings/components/DatabaseStorageCapacityWarning/DatabaseStorageCapacityWarning.tsx
- dashboard/src/features/orgs/projects/database/settings/components/DatabaseStorageCapacityWarning/index.ts
Resolves #3049
___
Enhancement
___
- Allow changing Postgres settings for paused projects
- Implement new warnings for disk size changes
- Improve validation for Postgres version selection
- Fix null subdomain error in project redirect
___
<tr>
<td>
<details>
<summary><strong>useProjectRedirectWhenReady.ts</strong><dd><code>Fix null subdomain error in project redirect</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/features/orgs/projects/common/hooks/useProjectRedirectWhenReady/useProjectRedirectWhenReady.ts
- Fixed null check for project.id to prevent error
</details>
</td> …
> feat (dashboard): allow to change postgres settings if project is paused

- .changeset/wet-pants-promise.md
- packages/hasura-storage-js/src/utils/upload.ts
Resolves #2440
___
Bug fix
___
- Corrected StorageErrorPayload TypeScript typing
- Refactored error handling in file upload
- Improved consistency of error object structure
- Added changeset for version bump
___
<tr>
<td>
<details>
<summary><strong>upload.ts</strong><dd><code>Refactor error handling in file upload</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/hasura-storage-js/src/utils/upload.ts
<li>Refactored error handling in <code>fetchUpload</code> function<br> <li> Created consistent <code>StorageErrorPayload</code> object<br> <li> …
> fix (dashboard): correct StorageErrorPayload TypeScript typing

- .github/workflows/ci.yaml
Enhancement, Tests
___
- Re-enable upgrade project e2e tests for dashboard
- Remove temporary comment disabling the tests
- Adjust CI workflow to include upgrade tests
___
```mermaid
flowchart LR
A["Disabled Tests"] -- "Re-enable" --> B["Upgrade Project E2E Tests"]
B -- "Include in" --> C["CI Workflow"]
```
<tr>
<td>
<details>
<summary><strong>ci.yaml</strong><dd><code>Re-enable Dashboard upgrade project e2e tests in CI</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/ci.yaml
<ul><li>Removed comments disabling upgrade project e2e tests<br> <li> Re-enabled the …
> chore (dashboard): re-enable upgrade project e2e tests

- dashboard/src/features/orgs/components/billing/components/SubscriptionPlan/SubscriptionPlan.tsx
Enhancement
___
- Disable upgrade to Starter plan
- Add visual cues for disabled Starter plan
- Improve user interface for plan selection
- Enhance accessibility and user experience
___
```mermaid
flowchart LR
A["Plan Selection"] --> B["Identify Starter Plan"]
B --> C["Disable Starter Option"]
C --> D["Visual Feedback"]
D --> E["Improved UX"]
```
<tr>
<td>
<details>
<summary><strong>SubscriptionPlan.tsx</strong><dd><code>Disable and style Starter plan in subscription selection</code>&nbsp; </dd></summary>
<hr>
dashboard/src/features/orgs/components/billing/components/SubscriptionPlan/SubscriptionPlan. …
> fix: dashboard: don't upgrade to starter

- .changeset/stupid-phones-act.md
- dashboard/src/pages/support/index.tsx
Bug fix
___
- Fixed scrolling issue on support page for Chrome iOS
- Changed container height from 'h-screen' to 'h-full'
- Added changeset for version tracking
___
```mermaid
flowchart LR
A["Support Page"] -- "Height Change" --> B["Full Scrolling"]
C["Changeset"] -- "Version Update" --> D["@nhost/dashboard"]
```
<tr>
<td>
<details>
<summary><strong>index.tsx</strong><dd><code>Adjust support page container height for better scrolling</code></dd></summary>
<hr>
dashboard/src/pages/support/index.tsx
<ul><li>Changed container height from 'h-screen' to 'h-full'<br> <li> Allows full scrolling on Chrome for …
> fix (dashboard): support page, can scroll all the way down in Chrome for iOS

- .changeset/cold-toys-bow.md
- dashboard/src/features/orgs/projects/database/dataGrid/components/DataBrowserSidebar/DataBrowserSidebar.tsx
- dashboard/src/features/orgs/projects/database/dataGrid/components/EditTableForm/EditTableForm.tsx
- dashboard/src/features/orgs/projects/database/dataGrid/utils/extractForeignKeyRelation/extractForeignKeyRelation.test.ts
- dashboard/src/features/orgs/projects/database/dataGrid/utils/extractForeignKeyRelation/extractForeignKeyRelation.ts
Bug fix, Tests
___
- Pass updated table name to refetch queries
- Extend `onSubmit` callbacks with `tableName`
- Strip quotes from foreign key column names
- Add and restructure tests for extractor
___
<tr>
<td>
<details>
<summary><strong>DataBrowserSidebar.tsx</strong><dd><code>Update refetchQueries with new tableName</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/features/orgs/projects/database/dataGrid/components/DataBrowserSidebar/DataBrowserSidebar.tsx
<ul><li>Accept …
> fix (dashboard): Parse foreign key relations correctly

- .changeset/dry-snails-type.md
- dashboard/src/components/ui/v3/fancy-multi-select.tsx
- dashboard/src/features/orgs/projects/database/dataGrid/components/RuleGroupEditor/RuleValueInput.test.tsx
- dashboard/src/features/orgs/projects/database/dataGrid/components/RuleGroupEditor/RuleValueInput.tsx
- dashboard/src/pages/signup.tsx
Bug fix, Tests, Enhancement
___
- Refactor FancyMultiSelect to controlled component
- Enhance RuleValueInput `_in` operator for system variables
- Add unit tests for RuleValueInput variable selection
- Include `Allowed-Ids` in permission variables list
___
```mermaid
flowchart LR
FV["Form value"]
GD["getDefaultValueForMultiSelect"]
FMS["FancyMultiSelect"]
OC["handleOnChange"]
SV["setValue"]
FV -- "parsed by" --> GD
GD -- "initializes" --> FMS
FMS -- "user selects" --> OC
OC -- "updates" --> SV
```
<tr>
<td>
<details>
<summary><strong>fancy-multi-select.tsx</strong><dd><code>Make FancyMultiSelect …
> fix (dashboard): allow permission variables with in operator

- .github/workflows/ci_create_release.yaml
- build/makefiles/release.makefile
Bug fix
___
- Add `cd $PROJECT` before make in CI workflow
- Ensure `make release-tag-name` runs in correct directory
___
```mermaid
flowchart LR
A["Extract VERSION"] --> B["Change to project directory"]
B --> C["Run make release-tag-name"]
C --> D["Set project_name output"]
```
<tr>
<td>
<details>
<summary><strong>ci_create_release.yaml</strong><dd><code>Change to project directory before make</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/ci_create_release.yaml
<ul><li>Insert …
> fix(ci): fixed ci_create_release.yaml

- .github/workflows/dashboard_wf_release.yaml
Bug fix
___
- Update PR body to reference inputs.VERSION
- Add base: main to the create-pull-request step
___
<tr>
<td>
<details>
<summary><strong>dashboard_wf_release.yaml</strong><dd><code>Use inputs.VERSION and set base to main</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/dashboard_wf_release.yaml
<ul><li>Changed PR body to use <code>inputs.VERSION</code> instead of dashboardVersion <br>output<br> <li> Added <code>base: main</code> to target the main branch</ul> …
> fix(ci): specify base when bumping the dashboard in the cli

- dashboard/src/features/orgs/projects/remote-schemas/components/BaseRemoteSchemaForm/GraphQLServiceURLInput.tsx
- dashboard/src/features/orgs/projects/remote-schemas/components/RemoteSchemaDetails/RemoteSchemaDetails.tsx
Enhancement
___
- Fix tooltip punctuation in `GraphQLServiceURLInput.tsx`
- Simplify `RemoteSchemaDetails.tsx` tooltip text
___
<tr>
<td>
<details>
<summary><strong>GraphQLServiceURLInput.tsx</strong><dd><code>Fix tooltip punctuation and formatting</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dashboard/src/features/orgs/projects/remote-schemas/components/BaseRemoteSchemaForm/GraphQLServiceURLInput.tsx
<ul><li>Added missing period after "remote schema."<br> <li> Inserted space before …
> fix(dashboard): update remote schemas url tooltip

- examples/docker-compose/.env.example
Documentation
___
- Add .env.example for docker-compose example
- Provide default service URLs environment variables
- Include security secrets and JWT config placeholders
___
<tr>
<td>
<details>
<summary><strong>.env.example</strong><dd><code>Add Docker Compose .env example file</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
examples/docker-compose/.env.example
<ul><li>Create new environment example file<br> <li> Add default service URL placeholders<br> <li> Define …
> fix(examples/docker-compose): added missing .env.example

- cli/dockercompose/auth.go
- cli/dockercompose/auth_test.go
Bug fix, Tests
___
- Disable TLS only when custom port is used
- Enable Traefik TLS label when TLS true
- Update tests to expect HTTPS URLs
___
```mermaid
flowchart LR
cfg["Config: useTLS & exposePort"]
gen["URL generation with TLS condition"]
env["Service ENV: AUTH_SERVER_URL"]
traefik["Traefik TLS label"]
test["Auth tests update"]
cfg -- "input to" --> gen
gen -- "produces" --> env
env -- "drives" --> traefik
traefik -- "verified by" --> test
```
<tr>
<td>
<details>
<summary><strong>auth.go</strong><dd><code>Integrate exposePort into TLS URL logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix(cli): disable tls on AUTH_SERVER_URL when auth uses custom port
